--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ACTIVITY_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_ACTIVITY_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_FREE_COMMENT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_BOARD_FREE_COMMENT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_FREE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_BOARD_FREE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_REGION_COMMENT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_BOARD_REGION_COMMENT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 69 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_REGION_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_BOARD_REGION_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 71 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMPLAIN_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_COMPLAIN_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DELETE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_DELETE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GAME_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_GAME_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER_REGISTER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_MEMBER_REGISTER_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTICE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_NOTICE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TEAM_REGISTER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_TEAM_REGISTER_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_WAIT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "DLEAGUE"."SEQ_WAIT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACTIVITY
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."ACTIVITY" 
   (	"ACTIVITY_NO" NUMBER, 
	"HOME" NVARCHAR2(15), 
	"AWAY" NVARCHAR2(15), 
	"PLACE" VARCHAR2(200 BYTE), 
	"ACTIVITYDATE" DATE, 
	"RESULT" NVARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_FREE
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."BOARD_FREE" 
   (	"BOARD_FREE_NO" NUMBER, 
	"BOARD_FREE_TITLE" VARCHAR2(50 BYTE), 
	"BOARD_FREE_WRITER" VARCHAR2(15 BYTE), 
	"BOARD_FREE_CONTENT" CLOB, 
	"BOARD_FREE_DATE" DATE, 
	"ORIGINAL_FILE_NAME" VARCHAR2(300 BYTE), 
	"RENAMED_FILE_NAME" VARCHAR2(300 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BOARD_FREE_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOARD_FREE_COMMENT
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."BOARD_FREE_COMMENT" 
   (	"BOARD_FREE_COMMENT_NO" NUMBER, 
	"BOARD_FREE_COMMENT_LEVEL" NUMBER, 
	"BOARD_FREE_COMMENT_WRITER" VARCHAR2(15 BYTE), 
	"BOARD_FREE_COMMENT_CONTENT" VARCHAR2(2000 BYTE), 
	"BOARD_FREE_REF" NUMBER, 
	"BOARD_FREE_COMMENT_REF" NUMBER, 
	"BOARD_FREE_COMMENT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_REGION
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."BOARD_REGION" 
   (	"BOARD_REGION_NO" NUMBER, 
	"BOARD_REGION_TITLE" VARCHAR2(50 BYTE), 
	"BOARD_REGION_WRITER" VARCHAR2(15 BYTE), 
	"BOARD_REGIONCODE" VARCHAR2(6 BYTE), 
	"BOARD_REGION_CONTENT" CLOB, 
	"BOARD_REGION_DATE" DATE, 
	"ORIGINAL_FILE_NAME" VARCHAR2(300 BYTE), 
	"RENAMED_FILE_NAME" VARCHAR2(300 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BOARD_REGION_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOARD_REGION_COMMENT
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."BOARD_REGION_COMMENT" 
   (	"BOARD_REGION_COMMENT_NO" NUMBER, 
	"BOARD_REGION_COMMENT_LEVEL" NUMBER, 
	"BOARD_REGION_COMMENT_WRITER" VARCHAR2(15 BYTE), 
	"BOARD_REGION_COMMENT_CONTENT" VARCHAR2(2000 BYTE), 
	"BOARD_REGION_REF" NUMBER, 
	"BOARD_REGION_COMMENT_REF" NUMBER, 
	"BOARD_REGION_COMMENT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPLAIN
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."COMPLAIN" 
   (	"COMPLAIN_NO" NUMBER, 
	"COMPLAIN_TITLE" VARCHAR2(100 BYTE), 
	"COMPLAIN_WRITER" VARCHAR2(15 BYTE), 
	"COMPLAIN_DATE" DATE, 
	"COMPLAIN_CONTENT" CLOB, 
	"C_USERID" VARCHAR2(15 BYTE), 
	"C_TEAMNAME" NVARCHAR2(15), 
	"COMPLAIN_TYPE" VARCHAR2(10 BYTE), 
	"RESULT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("COMPLAIN_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GAME
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."GAME" 
   (	"GAME_NO" NUMBER, 
	"HOME" NVARCHAR2(15), 
	"AWAY" NVARCHAR2(15), 
	"GAMEDATE" DATE, 
	"GAME_REG_DATE" DATE DEFAULT sysdate, 
	"PLACE" VARCHAR2(200 BYTE), 
	"START_TIME" VARCHAR2(20 BYTE), 
	"GAME_CONTENT" CLOB, 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("GAME_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MEMBER_REGISTER
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."MEMBER_REGISTER" 
   (	"MEMBER_REGISTER_NO" NUMBER, 
	"USERID" VARCHAR2(15 BYTE), 
	"TEAMNAME" NVARCHAR2(15), 
	"MESSAGE" VARCHAR2(4000 BYTE), 
	"REGISTER_DATE" DATE, 
	"YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."NOTICE" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(100 BYTE), 
	"NOTICE_WRITER" VARCHAR2(15 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(4000 BYTE), 
	"NOTICE_DATE" DATE, 
	"ORIGINAL_FILE_NAME" VARCHAR2(300 BYTE), 
	"RENAMED_FILE_NAME" VARCHAR2(300 BYTE), 
	"STATUS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."REGION" 
   (	"REGIONCODE" VARCHAR2(6 BYTE), 
	"REGIONNAME" NVARCHAR2(2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DELETE_USER
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."TBL_DELETE_USER" 
   (	"DELETE_NO" NUMBER, 
	"USERID" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"USERNAME" NVARCHAR2(5), 
	"REGIONCODE" VARCHAR2(6 BYTE), 
	"PHONE" NVARCHAR2(11), 
	"PROFILE" VARCHAR2(4000 BYTE), 
	"PHOTO" VARCHAR2(300 BYTE), 
	"DELETEDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_USER
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."TBL_USER" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"USERNAME" NVARCHAR2(5), 
	"REGIONCODE" VARCHAR2(6 BYTE), 
	"PHONE" NVARCHAR2(11), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TEAMNAME" NVARCHAR2(15), 
	"PROFILE" VARCHAR2(4000 BYTE), 
	"GRADE" NVARCHAR2(5) DEFAULT '선수', 
	"PHOTO" VARCHAR2(300 BYTE) DEFAULT 'default.jpg', 
	"ENROLLDATE" DATE DEFAULT SYSDATE, 
	"BIRTHDAY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."TEAM" 
   (	"TEAMNAME" NVARCHAR2(15), 
	"REGIONCODE" VARCHAR2(6 BYTE), 
	"CAPTAIN" VARCHAR2(15 BYTE), 
	"TEAMLOGO" VARCHAR2(300 BYTE) DEFAULT 'default.jpg', 
	"INTRODUCE" CLOB, 
	"FOUNDINGDATE" DATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("INTRODUCE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TEAM_MEMBER
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."TEAM_MEMBER" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"TEAMNAME" NVARCHAR2(15), 
	"T_ENROLLDATE" DATE, 
	"CLASS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAM_REGISTER
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."TEAM_REGISTER" 
   (	"TEAM_REGISTER_NO" NUMBER, 
	"TEAMNAME" NVARCHAR2(15), 
	"T_REGISTER_WRITER" VARCHAR2(15 BYTE), 
	"REGIONCODE" VARCHAR2(6 BYTE), 
	"TEAMLOGO" VARCHAR2(300 BYTE), 
	"INTRODUCE" CLOB, 
	"REGISTER_MSG" VARCHAR2(4000 BYTE), 
	"REGISTER_DATE" DATE, 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("INTRODUCE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table WAITTEAM
--------------------------------------------------------

  CREATE TABLE "DLEAGUE"."WAITTEAM" 
   (	"WAIT_NO" NUMBER, 
	"TEAMNAME" NVARCHAR2(15), 
	"GAME_NO" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DLEAGUE.ACTIVITY
SET DEFINE OFF;
REM INSERTING into DLEAGUE.BOARD_FREE
SET DEFINE OFF;
REM INSERTING into DLEAGUE.BOARD_FREE_COMMENT
SET DEFINE OFF;
REM INSERTING into DLEAGUE.BOARD_REGION
SET DEFINE OFF;
Insert into DLEAGUE.BOARD_REGION (BOARD_REGION_NO,BOARD_REGION_TITLE,BOARD_REGION_WRITER,BOARD_REGIONCODE,BOARD_REGION_DATE,ORIGINAL_FILE_NAME,RENAMED_FILE_NAME,STATUS,COUNT) values (70,'ㄶㅎ','yeon','G1',to_date('18/05/11','RR/MM/DD'),null,null,'Y',1);
REM INSERTING into DLEAGUE.BOARD_REGION_COMMENT
SET DEFINE OFF;
REM INSERTING into DLEAGUE.COMPLAIN
SET DEFINE OFF;
REM INSERTING into DLEAGUE.GAME
SET DEFINE OFF;
REM INSERTING into DLEAGUE.MEMBER_REGISTER
SET DEFINE OFF;
REM INSERTING into DLEAGUE.NOTICE
SET DEFINE OFF;
REM INSERTING into DLEAGUE.REGION
SET DEFINE OFF;
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G1','서울');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G2','경기');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G3','강원');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G4','충북');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G5','충남');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G6','경북');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G7','전북');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G8','전남');
Insert into DLEAGUE.REGION (REGIONCODE,REGIONNAME) values ('G9','제주');
REM INSERTING into DLEAGUE.TBL_DELETE_USER
SET DEFINE OFF;
REM INSERTING into DLEAGUE.TBL_USER
SET DEFINE OFF;
Insert into DLEAGUE.TBL_USER (USERID,PASSWORD,USERNAME,REGIONCODE,PHONE,EMAIL,TEAMNAME,PROFILE,GRADE,PHOTO,ENROLLDATE,BIRTHDAY) values ('admin','1234','admin','G2','01027809071','raccoon200@naver.com',null,'관리자관리자','관리자','default.jpg',to_date('18/05/08','RR/MM/DD'),'930322');
Insert into DLEAGUE.TBL_USER (USERID,PASSWORD,USERNAME,REGIONCODE,PHONE,EMAIL,TEAMNAME,PROFILE,GRADE,PHOTO,ENROLLDATE,BIRTHDAY) values ('yeon','1234','yeon','G1','01011112222','ydusrud1011@naver.com',null,'연경','선수','default.jpg',to_date('18/05/09','RR/MM/DD'),'930322');
REM INSERTING into DLEAGUE.TEAM
SET DEFINE OFF;
REM INSERTING into DLEAGUE.TEAM_MEMBER
SET DEFINE OFF;
REM INSERTING into DLEAGUE.TEAM_REGISTER
SET DEFINE OFF;
REM INSERTING into DLEAGUE.WAITTEAM
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ACTIVITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_ACTIVITY" ON "DLEAGUE"."ACTIVITY" ("ACTIVITY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_FREE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_BOARD_FREE" ON "DLEAGUE"."BOARD_FREE" ("BOARD_FREE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_BOARD_REGION" ON "DLEAGUE"."BOARD_REGION" ("BOARD_REGION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_REGION_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_BOARD_REGION_COMMENT" ON "DLEAGUE"."BOARD_REGION_COMMENT" ("BOARD_REGION_COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COMPLAIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_COMPLAIN" ON "DLEAGUE"."COMPLAIN" ("COMPLAIN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FREE_FREE_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_FREE_FREE_COMMENT" ON "DLEAGUE"."BOARD_FREE_COMMENT" ("BOARD_FREE_COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_GAME" ON "DLEAGUE"."GAME" ("GAME_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_REGISTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_MEMBER_REGISTER" ON "DLEAGUE"."MEMBER_REGISTER" ("MEMBER_REGISTER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_NOTICE" ON "DLEAGUE"."NOTICE" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_REGION" ON "DLEAGUE"."REGION" ("REGIONCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DELETE_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_TBL_DELETE_USER" ON "DLEAGUE"."TBL_DELETE_USER" ("DELETE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_TBL_USER" ON "DLEAGUE"."TBL_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TEAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_TEAM" ON "DLEAGUE"."TEAM" ("TEAMNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TEAM_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_TEAM_MEMBER" ON "DLEAGUE"."TEAM_MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TEAM_REGISTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_TEAM_REGISTER" ON "DLEAGUE"."TEAM_REGISTER" ("TEAM_REGISTER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_WAITTEAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "DLEAGUE"."PK_WAITTEAM" ON "DLEAGUE"."WAITTEAM" ("WAIT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."ACTIVITY" ADD CONSTRAINT "PK_ACTIVITY" PRIMARY KEY ("ACTIVITY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."ACTIVITY" MODIFY ("RESULT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."ACTIVITY" MODIFY ("ACTIVITYDATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."ACTIVITY" MODIFY ("PLACE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."ACTIVITY" MODIFY ("AWAY" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."ACTIVITY" MODIFY ("HOME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."ACTIVITY" MODIFY ("ACTIVITY_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_FREE
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."BOARD_FREE" ADD CONSTRAINT "PK_BOARD_FREE" PRIMARY KEY ("BOARD_FREE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("BOARD_FREE_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("BOARD_FREE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("BOARD_FREE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("BOARD_FREE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE" MODIFY ("BOARD_FREE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_FREE_COMMENT
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" ADD CONSTRAINT "PK_FREE_FREE_COMMENT" PRIMARY KEY ("BOARD_FREE_COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" MODIFY ("BOARD_FREE_COMMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" MODIFY ("BOARD_FREE_COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" MODIFY ("BOARD_FREE_COMMENT_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" MODIFY ("BOARD_FREE_COMMENT_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" MODIFY ("BOARD_FREE_COMMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_REGION
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."BOARD_REGION" ADD CONSTRAINT "PK_BOARD_REGION" PRIMARY KEY ("BOARD_REGION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("BOARD_REGION_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("BOARD_REGION_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("BOARD_REGIONCODE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("BOARD_REGION_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("BOARD_REGION_TITLE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION" MODIFY ("BOARD_REGION_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_REGION_COMMENT
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" ADD CONSTRAINT "PK_BOARD_REGION_COMMENT" PRIMARY KEY ("BOARD_REGION_COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" MODIFY ("BOARD_REGION_COMMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" MODIFY ("BOARD_REGION_COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" MODIFY ("BOARD_REGION_COMMENT_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" MODIFY ("BOARD_REGION_COMMENT_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" MODIFY ("BOARD_REGION_COMMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPLAIN
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."COMPLAIN" ADD CONSTRAINT "PK_COMPLAIN" PRIMARY KEY ("COMPLAIN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."COMPLAIN" MODIFY ("COMPLAIN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."COMPLAIN" MODIFY ("COMPLAIN_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."COMPLAIN" MODIFY ("COMPLAIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."COMPLAIN" MODIFY ("COMPLAIN_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."COMPLAIN" MODIFY ("COMPLAIN_TITLE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."COMPLAIN" MODIFY ("COMPLAIN_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GAME
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."GAME" ADD CONSTRAINT "PK_GAME" PRIMARY KEY ("GAME_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."GAME" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."GAME" MODIFY ("PLACE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."GAME" MODIFY ("GAME_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."GAME" MODIFY ("GAMEDATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."GAME" MODIFY ("HOME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."GAME" MODIFY ("GAME_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_REGISTER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" ADD CONSTRAINT "PK_MEMBER_REGISTER" PRIMARY KEY ("MEMBER_REGISTER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" MODIFY ("REGISTER_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" MODIFY ("MEMBER_REGISTER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."NOTICE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."NOTICE" MODIFY ("NOTICE_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."NOTICE" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."NOTICE" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."NOTICE" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."REGION" ADD CONSTRAINT "PK_REGION" PRIMARY KEY ("REGIONCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."REGION" MODIFY ("REGIONNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."REGION" MODIFY ("REGIONCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DELETE_USER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" ADD CONSTRAINT "PK_TBL_DELETE_USER" PRIMARY KEY ("DELETE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("DELETEDATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("REGIONCODE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" MODIFY ("DELETE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_USER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" ADD CONSTRAINT "PK_TBL_USER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("ENROLLDATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("REGIONCODE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TBL_USER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TEAM" ADD CONSTRAINT "PK_TEAM" PRIMARY KEY ("TEAMNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."TEAM" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM" MODIFY ("FOUNDINGDATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM" MODIFY ("INTRODUCE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM" MODIFY ("CAPTAIN" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM" MODIFY ("REGIONCODE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM" MODIFY ("TEAMNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM_MEMBER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" ADD CONSTRAINT "PK_TEAM_MEMBER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" MODIFY ("T_ENROLLDATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM_REGISTER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" ADD CONSTRAINT "PK_TEAM_REGISTER" PRIMARY KEY ("TEAM_REGISTER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" MODIFY ("REGISTER_DATE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" MODIFY ("REGIONCODE" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" MODIFY ("T_REGISTER_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" MODIFY ("TEAM_REGISTER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WAITTEAM
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."WAITTEAM" ADD CONSTRAINT "PK_WAITTEAM" PRIMARY KEY ("WAIT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DLEAGUE"."WAITTEAM" MODIFY ("GAME_NO" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."WAITTEAM" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "DLEAGUE"."WAITTEAM" MODIFY ("WAIT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."ACTIVITY" ADD CONSTRAINT "FK_GAME_TO_ACTIVITY" FOREIGN KEY ("ACTIVITY_NO")
	  REFERENCES "DLEAGUE"."GAME" ("GAME_NO") ENABLE;
  ALTER TABLE "DLEAGUE"."ACTIVITY" ADD CONSTRAINT "FK_TEAM_TO_ACTIVITY" FOREIGN KEY ("HOME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
  ALTER TABLE "DLEAGUE"."ACTIVITY" ADD CONSTRAINT "FK_TEAM_TO_ACTIVITY2" FOREIGN KEY ("AWAY")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_FREE_COMMENT
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" ADD CONSTRAINT "FK_FREE_FREE_COMMENT_REF" FOREIGN KEY ("BOARD_FREE_COMMENT_REF")
	  REFERENCES "DLEAGUE"."BOARD_FREE_COMMENT" ("BOARD_FREE_COMMENT_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DLEAGUE"."BOARD_FREE_COMMENT" ADD CONSTRAINT "FK_FREE_FREE_REF" FOREIGN KEY ("BOARD_FREE_REF")
	  REFERENCES "DLEAGUE"."BOARD_FREE" ("BOARD_FREE_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_REGION_COMMENT
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" ADD CONSTRAINT "FK_BOARD_REGION_COMMENT_REF" FOREIGN KEY ("BOARD_REGION_COMMENT_REF")
	  REFERENCES "DLEAGUE"."BOARD_REGION_COMMENT" ("BOARD_REGION_COMMENT_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DLEAGUE"."BOARD_REGION_COMMENT" ADD CONSTRAINT "FK_BOARD_REGION_REF" FOREIGN KEY ("BOARD_REGION_REF")
	  REFERENCES "DLEAGUE"."BOARD_REGION" ("BOARD_REGION_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPLAIN
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."COMPLAIN" ADD CONSTRAINT "FK_TBL_USER_TO_COMPLAIN" FOREIGN KEY ("C_USERID")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
  ALTER TABLE "DLEAGUE"."COMPLAIN" ADD CONSTRAINT "FK_TBL_USER_TO_COMPLAIN2" FOREIGN KEY ("COMPLAIN_WRITER")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
  ALTER TABLE "DLEAGUE"."COMPLAIN" ADD CONSTRAINT "FK_TEAM_TO_COMPLAIN" FOREIGN KEY ("C_TEAMNAME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GAME
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."GAME" ADD CONSTRAINT "FK_TEAM_TO_GAME" FOREIGN KEY ("HOME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
  ALTER TABLE "DLEAGUE"."GAME" ADD CONSTRAINT "FK_TEAM_TO_GAME2" FOREIGN KEY ("AWAY")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_REGISTER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" ADD CONSTRAINT "FK_TBL_USER_TO_MEMBER_REGISTER" FOREIGN KEY ("USERID")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
  ALTER TABLE "DLEAGUE"."MEMBER_REGISTER" ADD CONSTRAINT "FK_TEAM_TO_MEMBER_REGISTER" FOREIGN KEY ("TEAMNAME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."NOTICE" ADD CONSTRAINT "FK_TBL_USER_TO_NOTICE" FOREIGN KEY ("NOTICE_WRITER")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DELETE_USER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TBL_DELETE_USER" ADD CONSTRAINT "FK_REGION_TO_TBL_DELETE_USER" FOREIGN KEY ("REGIONCODE")
	  REFERENCES "DLEAGUE"."REGION" ("REGIONCODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TBL_USER" ADD CONSTRAINT "FK_REGION_TO_TBL_USER" FOREIGN KEY ("REGIONCODE")
	  REFERENCES "DLEAGUE"."REGION" ("REGIONCODE") ENABLE;
  ALTER TABLE "DLEAGUE"."TBL_USER" ADD CONSTRAINT "FK_TEAM_TO_TBL_USER" FOREIGN KEY ("TEAMNAME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TEAM" ADD CONSTRAINT "FK_REGION_TO_TEAM" FOREIGN KEY ("REGIONCODE")
	  REFERENCES "DLEAGUE"."REGION" ("REGIONCODE") ENABLE;
  ALTER TABLE "DLEAGUE"."TEAM" ADD CONSTRAINT "FK_TBL_USER_TO_TEAM" FOREIGN KEY ("CAPTAIN")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAM_MEMBER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" ADD CONSTRAINT "FK_TBL_USER_TO_TEAM_MEMBER" FOREIGN KEY ("USERID")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
  ALTER TABLE "DLEAGUE"."TEAM_MEMBER" ADD CONSTRAINT "FK_TEAM_TO_TEAM_MEMBER" FOREIGN KEY ("TEAMNAME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAM_REGISTER
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" ADD CONSTRAINT "FK_REGION_TO_TEAM_REGISTER" FOREIGN KEY ("REGIONCODE")
	  REFERENCES "DLEAGUE"."REGION" ("REGIONCODE") ENABLE;
  ALTER TABLE "DLEAGUE"."TEAM_REGISTER" ADD CONSTRAINT "FK_TBL_USER_TO_TEAM_REGISTER" FOREIGN KEY ("T_REGISTER_WRITER")
	  REFERENCES "DLEAGUE"."TBL_USER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WAITTEAM
--------------------------------------------------------

  ALTER TABLE "DLEAGUE"."WAITTEAM" ADD CONSTRAINT "FK_GAME_TO_WAITTEAM" FOREIGN KEY ("GAME_NO")
	  REFERENCES "DLEAGUE"."GAME" ("GAME_NO") ENABLE;
  ALTER TABLE "DLEAGUE"."WAITTEAM" ADD CONSTRAINT "FK_TEAM_TO_WAITTEAM" FOREIGN KEY ("TEAMNAME")
	  REFERENCES "DLEAGUE"."TEAM" ("TEAMNAME") ENABLE;
