/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-16 04:24:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.game;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dleague.search.model.vo.TeamMember;
import java.util.List;
import com.dleague.search.model.vo.Team;
import com.dleague.search.model.vo.Activity;
import com.dleague.game.model.vo.Game;
import com.dleague.member.model.vo.*;
import com.dleague.member.model.vo.*;

public final class myGameView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1526442460339L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1526442460437L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1526372379452L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.dleague.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dleague.search.model.vo.TeamMember");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dleague.game.model.vo.Game");
    _jspx_imports_classes.add("com.dleague.search.model.vo.Team");
    _jspx_imports_classes.add("com.dleague.search.model.vo.Activity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
   String param = (String)request.getAttribute("param");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Do+Hyeon|Nanum+Gothic\" rel=\"stylesheet\">\r\n");
      out.write("<title>DLeague</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\theader#header{ \r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height:119px; \r\n");
      out.write("\t    padding:10px 0 0 0;\r\n");
      out.write("\t    background: white;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t    top: 0px;\r\n");
      out.write("\t    left: 0px;\r\n");
      out.write("\t    border-bottom: 1px solid #f3f3f3;\r\n");
      out.write("\t    z-index: 150;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#header-div{\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height:41px;\r\n");
      out.write("\t    background: #f3f3f3;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t    top: 0px;\r\n");
      out.write("\t    left: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.header-div-wrap{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    height: 41px;\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    background: #f3f3f3;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.header-div-wrapping-nav{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    height: 77px;\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    background: white;\r\n");
      out.write("\t    top: 31px;\r\n");
      out.write("\t}\r\n");
      out.write("\timg#header-image{\r\n");
      out.write("\t    height: 77px;\r\n");
      out.write("\t}\r\n");
      out.write("\theader#header nav{\r\n");
      out.write("\t    float: right;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.main-nav{\r\n");
      out.write("\t    display:table;\r\n");
      out.write("\t    padding:0px; /*ul태그가 가진 기본padding초기화*/\r\n");
      out.write("\t    margin-top: 23px;\r\n");
      out.write("\t    margin-bottom: 0px;\r\n");
      out.write("\t    vertical-align: baseline;\r\n");
      out.write("\t    list-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-list{\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding-top: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover{\r\n");
      out.write("\t    border-bottom: 3px solid rgb(64,128,183); \r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover>div{\r\n");
      out.write("\t    border-top: 3px solid rgb(64,128,183); \r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover>a{\r\n");
      out.write("\t    color: rgb(64,128,183); \r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover div.main-nav-sub{\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-list>a{\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    padding: 0 0 19px;\r\n");
      out.write("\t    margin: 0 35px;\r\n");
      out.write("\t    font-size: 20px;\r\n");
      out.write("\t    color: #121212;\r\n");
      out.write("\t    font-family: 'Do Hyeon', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-list>a:link{\r\n");
      out.write("\t    text-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\tul#header-list {\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    float:right;\r\n");
      out.write("\t    display:table;\r\n");
      out.write("\t    padding:0px; /*ul태그가 가진 기본padding초기화*/\r\n");
      out.write("\t    margin:auto;\r\n");
      out.write("\t    margin-top: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul#header-list li{\r\n");
      out.write("\t    display:inline;\r\n");
      out.write("\t    list-style-type:none;\r\n");
      out.write("\t    padding:10px;\r\n");
      out.write("\t    font-size: 11px;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\tul#header-list li a{\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t    font-size: 9px;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    color:black;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-sub-li{\r\n");
      out.write("\t    list-style-type:none;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    padding-bottom: 10px;\r\n");
      out.write("\t    padding-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-sub-ul{\r\n");
      out.write("\t    padding: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.main-nav-sub{\r\n");
      out.write("\t    border: 1px solid rgb(64,128,183);\r\n");
      out.write("\t    display: none;\r\n");
      out.write("\t    background: white;\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-sub-li a{\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t    font-size: 15px;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    color:black;\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-sub-li:hover{\r\n");
      out.write("\t    background: rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-sub-li:hover>a{\r\n");
      out.write("\t    color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*section-center*/\r\n");
      out.write("\tsection#center{\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    min-height: 960px;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    padding-top: 168px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tnav#nav{\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    width: 175px;\r\n");
      out.write("\t    padding: 12px 0 0 14px;\r\n");
      out.write("\t    margin-right: 45px;\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\th3#nav-header{\r\n");
      out.write("\t    font-size: 23px;\r\n");
      out.write("\t    width: 115px;\r\n");
      out.write("\t    margin: 0 0 30px 15px;\r\n");
      out.write("\t    padding-bottom: 25px;\r\n");
      out.write("\t    border-bottom: 4px solid rgb(64,128,183);\r\n");
      out.write("\t    color: #111;\r\n");
      out.write("\t    line-height: 1.3;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list{\r\n");
      out.write("\t    margin-left: 15px;\r\n");
      out.write("\t    list-style: none;\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t    margin-left: 15px; \r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t    border: 0;\r\n");
      out.write("\t    font: inherit;\r\n");
      out.write("\t    vertical-align: baseline;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list li{\r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t    margin-bottom: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list li>a{\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    font-size: 17px;\r\n");
      out.write("\t    color: #7c7c7c;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\ta#nav-selected{\r\n");
      out.write("\t    color: rgb(64,128,183);\r\n");
      out.write("\t    font-weight: bolder;\r\n");
      out.write("\t}\r\n");
      out.write("\tsection#content{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    display:inline-block;\r\n");
      out.write("\t    margin:2px;\r\n");
      out.write("\t    width:750px;\r\n");
      out.write("\t    min-height: 300px;\r\n");
      out.write("\t    background:white;\r\n");
      out.write("\t    padding-left:10px;\r\n");
      out.write("\t    left: 206px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list li>a:hover{\r\n");
      out.write("\t    font-weight: bolder;\r\n");
      out.write("\t    color: rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tul.main-nav>li.main-nav-list a#header-selected{\r\n");
      out.write("\t    color:rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tul.main-nav>li.header-selected{\r\n");
      out.write("\t    border-bottom: 3px solid rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter#footer{\r\n");
      out.write("\t    background:#222;\r\n");
      out.write("\t    padding:5px;\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    height: 220px;\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter#footer p {\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    color:gray;\r\n");
      out.write("\t    text-align:center;\r\n");
      out.write("\t    font-size:15px;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    top: 80px;\r\n");
      out.write("\t    left: 307px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#footer-wrapper{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    height: 220px;\r\n");
      out.write("\t    margin: 0 auto;         \r\n");
      out.write("\t}\r\n");
      out.write("\timg#footer-image{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    height: 77px;\r\n");
      out.write("\t    top: 54px;\r\n");
      out.write("\t    left: 170px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("<script>\r\n");
if(memberLoggedIn!=null) { 
      out.write(" \r\n");
      out.write("   function fn_validate_team_info() {\r\n");
      out.write("      if(");
      out.print(memberLoggedIn.getTeamname());
      out.write("!=null) {\r\n");
      out.write("         return true;   \r\n");
      out.write("      }\r\n");
      out.write("      if(confirm(\"팀이 없습니다. 팀 생성 하시겠습니까??\")) location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamCreate\";\r\n");
      out.write("\r\n");
      out.write("      return false;\r\n");
      out.write("   }\r\n");
} 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <div id=\"header-div\">\r\n");
      out.write("            <div class=\"header-div-wrap\">\r\n");
      out.write("                <ul id=\"header-list\">\r\n");
      out.write("\t\t\t\t");
if(memberLoggedIn==null) {
      out.write("\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t    <li>|</li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginPage\">로그인</a></li>\r\n");
      out.write("\t\t\t\t ");
} else if("admin".equals(memberLoggedIn.getUserId())) { 
      out.write("\r\n");
      out.write("\t\t\t\t    <li>");
      out.print(memberLoggedIn.getUserId() );
      out.write("님 환영합니다!</li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t    <li>|</li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminPage\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t ");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t    <li>");
      out.print(memberLoggedIn.getUserId() );
      out.write("님 환영합니다!</li>\r\n");
      out.write("\t\t\t\t       <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"header-div-wrapping-nav\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img id=\"header-image\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/headerImage.png\" /></a>\r\n");
      out.write("            <nav>\r\n");
      out.write("            <ul class=\"main-nav\">\r\n");
      out.write("\t\t\t   <li id=\"main-nav-notice\" class=\"main-nav-list \"><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("               \r\n");
      out.write("               <li id=\"main-nav-board\" class='main-nav-list ");
      out.print(param=="freeBoard"||param=="regionBoard"||param=="complainBoard"?"header-selected":"");
      out.write("'>\r\n");
      out.write("                   <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/freeBoard\" id='");
      out.print(param=="freeBoard"||param=="regionBoard"||param=="complainBoard"?"header-selected":"");
      out.write("'>게시판</a>\r\n");
      out.write("                   <div class=\"main-nav-sub\" id=\"main-nav-sub-board\">\r\n");
      out.write("                       <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                           <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/freeBoard\" >자유게시판</a></li>\r\n");
      out.write("                           <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/regionBoard\" >지역게시판</a></li>\r\n");
      out.write("                           <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/complainBoard\">신고게시판</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </div>  \r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"main-nav-register\" class='main-nav-list ");
      out.print(param=="gameRegister"||param=="myGameList"?"header-selected":"");
      out.write("'>\r\n");
      out.write("               \t  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/gameRegister\" id='");
      out.print(param=="gameRegister"||param=="myGameList"?"header-selected":"");
      out.write("'>경기등록</a>\r\n");
      out.write("                  <!-- 경기등록  -->\r\n");
      out.write("                  <div class=\"main-nav-sub\" id=\"main-nav-sub-register\">\r\n");
      out.write("                     <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/gameRegister\">경기등록</a></li>\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/myGameList\">내팀경기일정</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"main-nav-search\" class='main-nav-list ");
      out.print(param=="teamSearch"?"header-selected":"");
      out.write("'>\r\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/teamSearch\" id='");
      out.print(param=="teamSearch"?"header-selected":"");
      out.write("'>검색</a>\r\n");
      out.write("                  <!-- 검색 -->\r\n");
      out.write("                  <div class=\"main-nav-sub\" id=\"main-nav-sub-search\">\r\n");
      out.write("                     <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/teamSearch\" >팀 검색</a></li>\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/gameSearchList\">경기 검색</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"main-nav-mypage\" class='main-nav-list ");
      out.print(param=="memberInfo"||param=="memberTeamInfo"?"header-selected":"");
      out.write("'>\r\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberInfoPage\" id='");
      out.print(param=="memberInfo"||param=="memberTeamInfo"?"header-selected":"");
      out.write("'>마이페이지</a>\r\n");
      out.write("                  <!-- 마이페이지 -->\r\n");
      out.write("                  <div class=\"main-nav-sub\" id=\"main-nav-sub-mypage\">\r\n");
      out.write("                     <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                         ");
if(memberLoggedIn!=null) {
      out.write(" \r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberInfoPage\">내 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamInfoPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" onclick=\"return fn_validate_team_info();\">내 팀 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamManagementPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\">내 팀 관리</a></li>\r\n");
      out.write("                        ");
 if("선수".equals(memberLoggedIn.getGrade())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamCreate\">팀생성</a><li>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                         ");
} 
      out.write(" \r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               \r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("         </nav>\r\n");
      out.write("         <!-- 메인메뉴 끝 -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("console.log(\"");
      out.print(param);
      out.write("\");\r\n");
      out.write("</script>\r\n");
      out.write("      <section id=\"center\">\r\n");
      out.write("\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 공지사항 -->\r\n");
      out.write("\t\t\t");
 if(param=="notice"){ 
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">공지사항</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a id=\"nav-selected\" href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t<!-- 게시판 -->\n");
      out.write("\t\t\t");
 if(param=="freeBoard" || param=="regionBoard" || param=="complain") {
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<h3 id=\"nav-header\">게시판</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a id='");
      out.print(param=="freeBoard"?"nav-selected":"");
      out.write("' href=\"");
      out.print(request.getContextPath() );
      out.write("/board/freeBoard\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t<li><a id='");
      out.print(param=="regionBoard"?"nav-selected":"");
      out.write("' href=\"");
      out.print(request.getContextPath() );
      out.write("/board/regionBoard\">지역게시판</a></li>\r\n");
      out.write("\t\t\t\t<li><a id='");
      out.print(param=="complainBoard"?"nav-selected":"");
      out.write("' href=\"");
      out.print(request.getContextPath() );
      out.write("/board/complainBoard\">신고게시판</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<!-- 로그인/회원가입 -->\r\n");
      out.write("\t\t\t");
if(param=="login" || param=="enroll") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">계정</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginPage\" id=id=");
      out.print(param=="login"?"nav-selected":"");
      out.write(">로그인</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" id=");
      out.print(param=="enroll"?"nav-selected":"");
      out.write(">회원가입</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="passwordCheck") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id = \"nav-header\">비밀번호 찾기</h3>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="passwordUpdate") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">비밀번호 변경</h3>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="gameRegister"||param=="myGameList") {
      out.write("\r\n");
      out.write("\t\t\t<!-- 경기등록  -->\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">경기등록</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/gameRegister\" id='");
      out.print(param=="gameRegister"?"nav-selected":"");
      out.write("'>경기등록</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/myGameList\" id='");
      out.print(param=="myGameList"?"nav-selected":"");
      out.write("'>내팀경기일정</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="teamSearch"||param=="teamSearchList") {
      out.write("\r\n");
      out.write("\t\t\t<!-- 검색 -->\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">검색</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/teamSearch\" id='");
      out.print(param=="teamSearch"?"nav-selected":"");
      out.write("'>팀검색</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/gameSearchList\" id='");
      out.print(param=="teamSearchList"?"nav-selected":"");
      out.write("'>경기검색</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="memberTeamMemberManagement" || param=="memberTeamGameAcceptPage") {
      out.write("\r\n");
      out.write("\t\t\t<h2 id=\"nav-header\">팀 관리</h2>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamManagement?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamMemberManagement"?"nav-selected":"");
      out.write("'>팀원 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">팀원 수락</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamGameAcceptPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamGameAcceptPage"?"nav-selected":"");
      out.write("'>팀 경기 수락</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="memberInfo" || param=="memberTeamInfo" || param=="memberTeamManagement") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">마이페이지</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberInfoPage\" id=\"");
      out.print(param=="memberInfo"?"nav-selected":"" );
      out.write("\" >내 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamInfoPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id=\"");
      out.print(param=="memberTeamInfo"?"nav-selected":"" );
      out.write("\">내 팀 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamManagementPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\" id=\"");
      out.print(param=="memberTeamManagement"?"nav-selected":"" );
      out.write("\">내 팀 관리</a></li>\r\n");
      out.write("\t\t\t</ul> \r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(param=="adminPage" || param=="adminPageTeam" ||param=="adminAccept") {
      out.write("\r\n");
      out.write("\t\t\t<!-- 관리자페이지 -->\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">관리자페이지</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/adminPage\" id=\"");
      out.print(param=="adminPage"?"nav-selected":"" );
      out.write("\" >회원 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/adminPageTeam\" id=\"");
      out.print(param=="adminPageTeam"?"nav-selected":"" );
      out.write("\">팀 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/adminAccept\" id=\"");
      out.print(param=="adminAccept"?"nav-selected":"" );
      out.write("\">팀 수락</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">접속 통계</a></li>\r\n");
      out.write("\t\t\t</ul>  \r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section id=\"content\">");
      out.write('\r');
      out.write('\n');

	Object o = request.getAttribute("obj");
	Activity a = null;
	Game g = null;
	String place[] = null;
	boolean gameStatus = o instanceof Game;
	if(gameStatus){
		g = (Game)o;
		place = g.getPlace().split("#");
	}else{
		a = (Activity)a;
		place = a.getPlace().split("#");
	}
	Team tHome = (Team)request.getAttribute("tHome");
	Team tAway = (Team)request.getAttribute("tAway");
	
	List <TeamMember> hMemberList = (List<TeamMember>)request.getAttribute("hMemberList");
	List <TeamMember> aMemberList = (List<TeamMember>)request.getAttribute("aMemberList");
	
	List <Activity> hActivityList = (List<Activity>)request.getAttribute("hActivityList");
	List <Activity> aActivityList = (List<Activity>)request.getAttribute("aActivityList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?clientId=f3nKBZeo1DvNZrIIPMNu&submodules=geocoder\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* body{\r\n");
      out.write("  margin-top: 100px;\r\n");
      out.write("  line-height: 1.6\r\n");
      out.write("} */\r\n");
      out.write(".container{\r\n");
      out.write("\twidth: 95%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("ul.tabs{\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("ul.tabs li{\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 10px 15px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("ul.tabs li.current{\r\n");
      out.write("  \tbackground: #ededed;\r\n");
      out.write("  \tcolor: #222;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".tab-content{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #ededed;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".tab-content.current{\r\n");
      out.write("  \tdisplay: inherit;\r\n");
      out.write("}\r\n");
      out.write("div#score{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin : 0 auto;\r\n");
      out.write("}\r\n");
      out.write("div.center{\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("\timg#logoimg{width: 250px;height: 200px;display: inline-block;margin: 50px 0 0 0;}\r\n");
      out.write("\timg#logo{width: 200px;height: 80px;display: inline-block;}\r\n");
      out.write("\tdiv#logoDiv{width: 200px;height: 80px;display: inline-block;}\r\n");
      out.write("\tdiv#imgDiv{width: 366px;height: 315px;display: inline-block;float: left;text-align:center;}\r\n");
      out.write("\t/* div#bu,#a,#b,#c,#d{border: 1px solid black;} */\r\n");
      out.write("\tdiv#bu{height: 590px; width: 644px; display: inline-block;}\r\n");
      out.write("\tdiv#a{border-radius: 10px;background:lightgreen;height: 100px; width: 200px; text-align: center; display: inline-block; margin:10px 0 0 0;}\r\n");
      out.write("\tdiv#b{border-radius: 10px;background:lightgreen;height: 80px; width: 200px; text-align: center; display: inline-block; margin:10px 0 0 0;}\r\n");
      out.write("\tdiv#c{border-radius: 10px;background:lightgreen;height: 80px; width: 200px;  text-align: center; display: inline-block; margin:10px 0 0 0;}\r\n");
      out.write("\tdiv#d{height: 80px; width: 200px; text-align: center; display: inline-block;}\r\n");
      out.write("\t/*글자색깔*/\r\n");
      out.write("\th2#aa{color:#2828CD;}\r\n");
      out.write("\th2#bb{color:#DB631F;}\r\n");
      out.write("\th3#bb{color:#DB631F;}\r\n");
      out.write("\t\r\n");
      out.write("    /* 테이블 공통 UI Object */\r\n");
      out.write("    th{text-align:center} /* 부트스트랩으로 센터로안옴 */\r\n");
      out.write("    .tbl_type,.tbl_type th,.tbl_type td{border:0}\r\n");
      out.write("    .tbl_type{border:1px;width:90%;border-bottom:2px solid #dcdcdc;font-family:'돋움',dotum;font-size:12px;text-align:center;border-collapse:collapse}\r\n");
      out.write("    .tbl_type caption{display:none}\r\n");
      out.write("    .tbl_type tfoot{background-color:#f5f7f9;font-weight:bold}\r\n");
      out.write("    .tbl_type th{padding:7px 0 4px;border-top:2px solid #dcdcdc;border-right:1px solid #dcdcdc;border-left:1px solid #dcdcdc;background-color:#f5f7f9;color:#666;font-family:'돋움',dotum;font-size:12px;font-weight:bold}\r\n");
      out.write("    .tbl_type td{padding:6px 0 4px;border:1px solid #e5e5e5;color:#4c4c4c}\r\n");
      out.write("    .tbl_type td.ranking{font-weight:bold}\r\n");
      out.write("    /* //테이블 공통 UI Object */\r\n");
      out.write("\r\n");
      out.write("    /*memberTable*/\r\n");
      out.write("    div#memberTable{width: 100%; display: inline-block;}\r\n");
      out.write("    /*memberTable*/\r\n");
      out.write("    /*teamTable*/\r\n");
      out.write("    div#teamTable{width: 100%; display: inline-block;}\r\n");
      out.write("    /*teamTable*/\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\tif(");
      out.print(memberLoggedIn == null);
      out.write("){\r\n");
      out.write("\t\talert(\"잘못된 경로입니다.\");\r\n");
      out.write("\t\tlocation.href=\"/\";\r\n");
      out.write("\t};\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<h2>경기 상세 정보</h2>\r\n");
      out.write("<hr />\r\n");
      out.write("<div id=\"score\">\r\n");
      out.write("\t<table style=\"display: inline-block;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/team/");
      out.print(gameStatus?g.getHomeLogo():a.getHomeLogo() );
      out.write("\" alt=\"home\" style=\"width: 150px; height: 112.188px;\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t<h1 style= \"display: inline-block; font-weight: 700; font-size: 70px; margin-left : 20px; margin-right : 60px;\">");
      out.print(gameStatus?"&nbsp;":a.getResult().substring(0, a.getResult().indexOf(":")));
      out.write("</h1>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t<h2 style=\"display: inline-block;\">VS</h2>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\">\r\n");
      out.write("\t\t\t\t<h1 style= \"display: inline-block; font-weight: 700; font-size: 70px; margin-left : 60px; margin-right : 20px;\">");
      out.print(gameStatus?"&nbsp;":a.getResult().substring(a.getResult().indexOf(":")+1, a.getResult().length()));
      out.write("</h1>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\" text-aline : center;\">\r\n");
      out.write("\t\t\t<td style='color: ");
      out.print(memberLoggedIn.getTeamname().equals(g.getHome())?"red":"");
      out.write("; font-size : 18px;'>\r\n");
      out.write("\t\t\t\t");
      out.print(gameStatus?g.getHome():a.getHome());
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table style=\"display: inline-block;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t");
if (gameStatus&&g.getAway()!= null) {
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/team/");
      out.print(g.getAwayLogo());
      out.write("\" alt=\"home\" style=\"width: 150px; height: 112.188px;\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t");
} else if (gameStatus && g.getAway() == null) {
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/team/awayNull.png\" alt=\"home\" style=\"width: 150px; height: 112.188px;\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/team/");
      out.print(a.getAwayLogo());
      out.write("\" alt=\"home\" style=\"width: 150px; height: 112.188px;\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\" text-aline : center;\">\r\n");
      out.write("\t\t\t<td style='color: ");
      out.print(memberLoggedIn.getTeamname().equals(g.getAway())?"red":"");
      out.write("; font-size : 18px;'>\r\n");
      out.write("\t\t\t\t");
if (gameStatus){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(g.getAway() !=null?g.getAway():"&nbsp;" );
      out.write("\t\r\n");
      out.write("\t\t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(a.getAway() );
      out.write("\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
if (gameStatus && g.getAway() == null){ 
      out.write("\r\n");
      out.write("\t<div class=\"alert alert-warning center\">\r\n");
      out.write("\t\t<strong style=\"font-size: 17px;\">");
      out.print(g.getGameDate() );
      out.write(' ');
      out.print(g.getStartTime() );
      out.write(" 상대 찾는중</strong>\r\n");
      out.write("\t</div>\r\n");
} else if(gameStatus && g.getAway() != null){ 
      out.write("\r\n");
      out.write("\t<div class=\"alert alert-info center\">\r\n");
      out.write("\t\t<strong style=\"font-size: 17px;\">");
      out.print(g.getGameDate() );
      out.write(' ');
      out.print(g.getStartTime() );
      out.write(" 경기 예정</strong>\r\n");
      out.write("\t</div>\r\n");
} else if(gameStatus && g.getStatus().equals("N")){ 
      out.write("\r\n");
      out.write("\t<div class=\"alert alert-danger center\">\r\n");
      out.write("\t\t<strong style=\"font-size: 17px;\">");
      out.print(g.getGameDate() );
      out.write(' ');
      out.print(g.getStartTime() );
      out.write(" 경기 미실시</strong>\r\n");
      out.write("\t</div>\r\n");
} else {
      out.write("\r\n");
      out.write("\t<div class=\"alert alert-success center\">\r\n");
      out.write("\t\t<strong style=\"font-size: 17px;\">");
      out.print(a.getActivityDate() );
      out.write(" 경기 완료</strong>\r\n");
      out.write("\t</div>\r\n");
} 
      out.write("\r\n");
      out.write("\t<ul class=\"tabs\">\r\n");
      out.write("\t  <li class=\"tab-link current\" data-tab=\"tab-1\">경기 정보</li>\r\n");
      out.write("\t  <li class=\"tab-link\" data-tab=\"tab-2\">홈팀 정보</li>\r\n");
      out.write("\t  <li class=\"tab-link\" data-tab=\"tab-3\">어웨이팀 정보</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"tab-1\" class=\"tab-content current\">\r\n");
      out.write("\t\t<h3>경기 장소</h3>\r\n");
      out.write("\t\t<hr style=\"background: white;\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(place[0]);
      out.write(' ');
      out.print(place[1] );
      out.write("\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t<div id=\"map\" style=\"width:100%;height:350px;\"></div>\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t");
if (gameStatus){ 
      out.write("\r\n");
      out.write("\t\t<h3>경기 내용</h3>\r\n");
      out.write("\t\t<hr style=\"background: white;\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<textarea class=\"form-control\" cols=\"60\" rows=\"10\" readonly>\r\n");
      out.print(g.getGameContent() );
      out.write("\r\n");
      out.write("\t\t</textarea>\r\n");
      out.write("\t\t");
 }
      out.write("\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<div id=\"tab-2\" class=\"tab-content\">\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t    <div id=\"bu\">\r\n");
      out.write("\t    \t<div id=\"imgDiv\">\r\n");
      out.write("\t        \t<img id=\"logoimg\" src=\r\n");
      out.write("\t        \t");
if(tHome.getTeamLogo()!=null){ 
      out.write("\r\n");
      out.write("\t        \t\t\"");
      out.print(request.getContextPath() );
      out.write("/images/team/");
      out.print(tHome.getTeamLogo() );
      out.write("\"\r\n");
      out.write("\t        \t");
}else{ 
      out.write("\r\n");
      out.write("\t        \t \t\"");
      out.print(request.getContextPath() );
      out.write("/images/team/default.png\" \r\n");
      out.write("\t        \t");
} 
      out.write("\r\n");
      out.write("\t        \t alt=\"첨부파일\"/>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div id=\"a\">\r\n");
      out.write("\t            <h2 id=\"bb\">팀이름</h2>\r\n");
      out.write("\t            <h4>");
      out.print(tHome.getTeamName() );
      out.write("</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br>\r\n");
      out.write("\t        <div id=\"b\">\r\n");
      out.write("\t            <h3 id=\"bb\">팀장</h3>\r\n");
      out.write("\t            <h4>");
      out.print(tHome.getCapTain()  );
      out.write("</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br>\r\n");
      out.write("\t        <div id=\"c\">\r\n");
      out.write("\t            <h3 id=\"bb\">팀원수</h3>\r\n");
      out.write("\t            <h4> ");
      out.print(hMemberList.size() );
      out.write("명</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br /> <br /><br />\r\n");
      out.write("\t        <div id=\"d\">\r\n");
      out.write("\t            <h2 id=\"aa\">활동지역</h2>\r\n");
      out.write("\t            <h3>\r\n");
      out.write("\t            \t");
if("G1".equals(tHome.getRegionCode()) ) {
      out.write("\r\n");
      out.write("\t        \t\t\t서울\r\n");
      out.write("\t        \t\t");
}else if("G2".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t경기\r\n");
      out.write("\t        \t\t");
}else if("G3".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t강원\r\n");
      out.write("\t        \t\t");
}else if("G4".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t충북\r\n");
      out.write("\t        \t\t");
}else if("G5".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t충남\r\n");
      out.write("\t        \t\t");
}else if("G6".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t경북\r\n");
      out.write("\t        \t\t");
}else if("G7".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t전북\r\n");
      out.write("\t        \t\t");
}else if("G8".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t전남\r\n");
      out.write("\t        \t\t");
}else if("G9".equals(tHome.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t제주\t\t\t\t\t\r\n");
      out.write("\t\t        \t");
} 
      out.write("\r\n");
      out.write("\t            </h3>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t         <div id=\"logoDiv\">\r\n");
      out.write("\t        \t<img id=\"logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/headerImage.jpg\" alt=\"첨부파일\"/>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t         <div id=\"d\">\r\n");
      out.write("\t            <h2 id=\"aa\">창단일</h2>\r\n");
      out.write("\t            <h3>");
      out.print(tHome.getFoundingDate() );
      out.write("</h3>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br><br>\r\n");
      out.write("\t        <textarea name=\"\" id=\"\" cols=\"85\" rows=\"7\" readonly style=\"resize: none\">");
      out.print(tHome.getIntroduce() );
      out.write("</textarea>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <br>\r\n");
      out.write("\t    <br />\r\n");
      out.write("\t    <div id=\"memberTable\">\r\n");
      out.write("\t    <!--ui object -->\r\n");
      out.write("\t    <table class=\"tbl_type\"  cellspacing=\"0\">\r\n");
      out.write("\t        <legend>◎팀원정보</legend>\r\n");
      out.write("\t        <colgroup>\r\n");
      out.write("\t            <col width=\"10%\"> \r\n");
      out.write("\t            <col width=\"15%\">\r\n");
      out.write("\t            <col width=\"10%\">\r\n");
      out.write("\t            <col width=\"10%\">\r\n");
      out.write("\t            <col width=\"15%\">\r\n");
      out.write("\t        </colgroup>\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t            <th scope=\"col\">순번</th>\r\n");
      out.write("\t            <th scope=\"col\">팀원</th>\r\n");
      out.write("\t            <th scope=\"col\">지역</th>\r\n");
      out.write("\t            <th scope=\"col\">등급</th>\r\n");
      out.write("\t            <th scope=\"col\">입단일</th>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t        <tbody>\r\n");
      out.write("\t        ");
for(TeamMember tm : hMemberList){ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t\t            <td class=\"ranking\" scope=\"row\">");
      out.print(tm.getRnum() );
      out.write("</td>\r\n");
      out.write("\t\t            <td>");
      out.print(tm.getUserId() );
      out.write("</td>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t            \t");
if("G1".equals(tm.getRegionCode()) ) {
      out.write("\r\n");
      out.write("\t\t        \t\t\t서울\r\n");
      out.write("\t\t        \t\t");
}else if("G2".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t경기\r\n");
      out.write("\t\t        \t\t");
}else if("G3".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t강원\r\n");
      out.write("\t\t        \t\t");
}else if("G4".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t충북\r\n");
      out.write("\t\t        \t\t");
}else if("G5".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t충남\r\n");
      out.write("\t\t        \t\t");
}else if("G6".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t경북\r\n");
      out.write("\t\t        \t\t");
}else if("G7".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t전북\r\n");
      out.write("\t\t        \t\t");
}else if("G8".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t전남\r\n");
      out.write("\t\t        \t\t");
}else if("G9".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t제주\t\t\t\t\t\r\n");
      out.write("\t\t        \t\t");
} 
      out.write("\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t            <td>");
      out.print(tm.getGrade() );
      out.write("</td>\r\n");
      out.write("\t\t            <td>");
      out.print(tm.getT_EnrollDate() );
      out.write("</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("\t        </tbody>\r\n");
      out.write("\t        <tfoot>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t            <td>종합</td>\r\n");
      out.write("\t            <td colspan=\"2\">총 팀원수</td>\r\n");
      out.write("\t            <td colspan=\"3\">");
      out.print(hMemberList.size());
      out.write("명</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            </tfoot>\r\n");
      out.write("\t        </table>\r\n");
      out.write("\t        <!--//ui object -->\r\n");
      out.write("\t    </div >\r\n");
      out.write("\t    <br /><br />\r\n");
      out.write("\t<div id=\"teamTable\">\r\n");
      out.write("\t        <!--ui object -->\r\n");
      out.write("\t        <table class=\"tbl_type\"  cellspacing=\"0\">\r\n");
      out.write("\t                <legend>◎팀활동내역</legend>\r\n");
      out.write("\t            <colgroup>\r\n");
      out.write("\t                <col width=\"10%\"> \r\n");
      out.write("\t                <col width=\"10%\">\r\n");
      out.write("\t                <col width=\"10%\">\r\n");
      out.write("\t                <col width=\"25%\">\r\n");
      out.write("\t                <col width=\"10%\">\r\n");
      out.write("\t            </colgroup>\r\n");
      out.write("\t            <thead>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <th scope=\"col\">게임번호</th>\r\n");
      out.write("\t                <th scope=\"col\">HomeTeam</th>\r\n");
      out.write("\t                <th scope=\"col\">AwayTeam</th>\r\n");
      out.write("\t                <th scope=\"col\">게임날짜</th>\r\n");
      out.write("\t                <th scope=\"col\">결과</th>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            </thead>\r\n");
      out.write("\t            <tbody>\r\n");
      out.write("\t            ");
if(hActivityList.size()==0||hActivityList == null){ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <td colspan=\"5\">데이터가 없습니다.</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            ");
}else{ 
      out.write("\r\n");
      out.write("\t            ");
for(Activity act: hActivityList){ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <td class=\"ranking\" scope=\"row\">");
      out.print(act.getActivity_No() );
      out.write("</td>\r\n");
      out.write("\t                <td style=\"color:");
      out.print(((act.getHome().equals(tHome))?"red":"black" ));
      out.write('"');
      out.write('>');
      out.print(a.getHome() );
      out.write("</td>\r\n");
      out.write("\t                <td style=\"color:");
      out.print(((act.getAway().equals(tHome))?"red":"black" ));
      out.write('"');
      out.write('>');
      out.print(a.getAway() );
      out.write("</td>\r\n");
      out.write("\t                <td>");
      out.print(act.getActivityDate() );
      out.write("</td>\r\n");
      out.write("\t                <td>");
      out.print(act.getResult() );
      out.write("</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            ");
}} 
      out.write("\r\n");
      out.write("\t            </tbody>\r\n");
      out.write("\t            <tfoot>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                <td colspan=\"5\">활동내역</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                </tfoot>\r\n");
      out.write("\t            </table>\r\n");
      out.write("\t            <!--//ui object -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<div id=\"tab-3\" class=\"tab-content\">\r\n");
      out.write("  \t");
if(tAway != null){ 
      out.write("\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t    <div id=\"bu\">\r\n");
      out.write("\t    \t<div id=\"imgDiv\">\r\n");
      out.write("\t        \t<img id=\"logoimg\" src=\r\n");
      out.write("\t        \t");
if(tAway.getTeamLogo()!=null){ 
      out.write("\r\n");
      out.write("\t        \t\t\"");
      out.print(request.getContextPath() );
      out.write("/images/team/");
      out.print(tAway.getTeamLogo() );
      out.write("\"\r\n");
      out.write("\t        \t");
}else{ 
      out.write("\r\n");
      out.write("\t        \t \t\"");
      out.print(request.getContextPath() );
      out.write("/images/team/default.png\" \r\n");
      out.write("\t        \t");
} 
      out.write("\r\n");
      out.write("\t        \t alt=\"첨부파일\"/>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div id=\"a\">\r\n");
      out.write("\t            <h2 id=\"bb\">팀이름</h2>\r\n");
      out.write("\t            <h4>");
      out.print(tAway.getTeamName() );
      out.write("</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br>\r\n");
      out.write("\t        <div id=\"b\">\r\n");
      out.write("\t            <h3 id=\"bb\">팀장</h3>\r\n");
      out.write("\t            <h4>");
      out.print(tAway.getCapTain()  );
      out.write("</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br>\r\n");
      out.write("\t        <div id=\"c\">\r\n");
      out.write("\t            <h3 id=\"bb\">팀원수</h3>\r\n");
      out.write("\t            <h4> ");
      out.print(aMemberList.size() );
      out.write("명</h4>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br /> <br /><br />\r\n");
      out.write("\t        <div id=\"d\">\r\n");
      out.write("\t            <h2 id=\"aa\">활동지역</h2>\r\n");
      out.write("\t            <h3>\r\n");
      out.write("\t            \t");
if("G1".equals(tAway.getRegionCode()) ) {
      out.write("\r\n");
      out.write("\t        \t\t\t서울\r\n");
      out.write("\t        \t\t");
}else if("G2".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t경기\r\n");
      out.write("\t        \t\t");
}else if("G3".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t강원\r\n");
      out.write("\t        \t\t");
}else if("G4".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t충북\r\n");
      out.write("\t        \t\t");
}else if("G5".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t충남\r\n");
      out.write("\t        \t\t");
}else if("G6".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t경북\r\n");
      out.write("\t        \t\t");
}else if("G7".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t전북\r\n");
      out.write("\t        \t\t");
}else if("G8".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t전남\r\n");
      out.write("\t        \t\t");
}else if("G9".equals(tAway.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t        \t\t\t제주\t\t\t\t\t\r\n");
      out.write("\t\t        \t");
} 
      out.write("\r\n");
      out.write("\t            </h3>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t         <div id=\"logoDiv\">\r\n");
      out.write("\t        \t<img id=\"logo\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/headerImage.jpg\" alt=\"첨부파일\"/>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t         <div id=\"d\">\r\n");
      out.write("\t            <h2 id=\"aa\">창단일</h2>\r\n");
      out.write("\t            <h3>");
      out.print(tAway.getFoundingDate() );
      out.write("</h3>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <br><br>\r\n");
      out.write("\t        <textarea name=\"\" id=\"\" cols=\"85\" rows=\"7\" readonly style=\"resize: none\">");
      out.print(tAway.getIntroduce() );
      out.write("</textarea>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <br>\r\n");
      out.write("\t    <br />\r\n");
      out.write("\t    <div id=\"memberTable\">\r\n");
      out.write("\t    <!--ui object -->\r\n");
      out.write("\t    <table class=\"tbl_type\"  cellspacing=\"0\">\r\n");
      out.write("\t        <legend>◎팀원정보</legend>\r\n");
      out.write("\t        <colgroup>\r\n");
      out.write("\t            <col width=\"10%\"> \r\n");
      out.write("\t            <col width=\"15%\">\r\n");
      out.write("\t            <col width=\"10%\">\r\n");
      out.write("\t            <col width=\"10%\">\r\n");
      out.write("\t            <col width=\"15%\">\r\n");
      out.write("\t        </colgroup>\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t            <th scope=\"col\">순번</th>\r\n");
      out.write("\t            <th scope=\"col\">팀원</th>\r\n");
      out.write("\t            <th scope=\"col\">지역</th>\r\n");
      out.write("\t            <th scope=\"col\">등급</th>\r\n");
      out.write("\t            <th scope=\"col\">입단일</th>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t        <tbody>\r\n");
      out.write("\t        ");
for(TeamMember tm : aMemberList){ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t\t            <td class=\"ranking\" scope=\"row\">");
      out.print(tm.getRnum() );
      out.write("</td>\r\n");
      out.write("\t\t            <td>");
      out.print(tm.getUserId() );
      out.write("</td>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t            \t");
if("G1".equals(tm.getRegionCode()) ) {
      out.write("\r\n");
      out.write("\t\t        \t\t\t서울\r\n");
      out.write("\t\t        \t\t");
}else if("G2".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t경기\r\n");
      out.write("\t\t        \t\t");
}else if("G3".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t강원\r\n");
      out.write("\t\t        \t\t");
}else if("G4".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t충북\r\n");
      out.write("\t\t        \t\t");
}else if("G5".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t충남\r\n");
      out.write("\t\t        \t\t");
}else if("G6".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t경북\r\n");
      out.write("\t\t        \t\t");
}else if("G7".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t전북\r\n");
      out.write("\t\t        \t\t");
}else if("G8".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t전남\r\n");
      out.write("\t\t        \t\t");
}else if("G9".equals(tm.getRegionCode()) ) { 
      out.write("\r\n");
      out.write("\t\t        \t\t\t제주\t\t\t\t\t\r\n");
      out.write("\t\t        \t\t");
} 
      out.write("\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t            <td>");
      out.print(tm.getGrade() );
      out.write("</td>\r\n");
      out.write("\t\t            <td>");
      out.print(tm.getT_EnrollDate() );
      out.write("</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("\t        </tbody>\r\n");
      out.write("\t        <tfoot>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t            <td>종합</td>\r\n");
      out.write("\t            <td colspan=\"2\">총 팀원수</td>\r\n");
      out.write("\t            <td colspan=\"3\">");
      out.print(aMemberList.size());
      out.write("명</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            </tfoot>\r\n");
      out.write("\t        </table>\r\n");
      out.write("\t        <!--//ui object -->\r\n");
      out.write("\t    </div >\r\n");
      out.write("\t    <br /><br />\r\n");
      out.write("\t<div id=\"teamTable\">\r\n");
      out.write("\t        <!--ui object -->\r\n");
      out.write("\t        <table class=\"tbl_type\"  cellspacing=\"0\">\r\n");
      out.write("\t                <legend>◎팀활동내역</legend>\r\n");
      out.write("\t            <colgroup>\r\n");
      out.write("\t                <col width=\"10%\"> \r\n");
      out.write("\t                <col width=\"10%\">\r\n");
      out.write("\t                <col width=\"10%\">\r\n");
      out.write("\t                <col width=\"25%\">\r\n");
      out.write("\t                <col width=\"10%\">\r\n");
      out.write("\t            </colgroup>\r\n");
      out.write("\t            <thead>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <th scope=\"col\">게임번호</th>\r\n");
      out.write("\t                <th scope=\"col\">HomeTeam</th>\r\n");
      out.write("\t                <th scope=\"col\">AwayTeam</th>\r\n");
      out.write("\t                <th scope=\"col\">게임날짜</th>\r\n");
      out.write("\t                <th scope=\"col\">결과</th>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            </thead>\r\n");
      out.write("\t            <tbody>\r\n");
      out.write("\t            ");
if(aActivityList.size()==0||aActivityList == null){ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <td colspan=\"5\">데이터가 없습니다.</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            ");
}else{ 
      out.write("\r\n");
      out.write("\t            ");
for(Activity act: hActivityList){ 
      out.write("\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <td class=\"ranking\" scope=\"row\">");
      out.print(act.getActivity_No() );
      out.write("</td>\r\n");
      out.write("\t                <td style=\"color:");
      out.print(((act.getHome().equals(tHome))?"red":"black" ));
      out.write('"');
      out.write('>');
      out.print(a.getHome() );
      out.write("</td>\r\n");
      out.write("\t                <td style=\"color:");
      out.print(((act.getAway().equals(tHome))?"red":"black" ));
      out.write('"');
      out.write('>');
      out.print(a.getAway() );
      out.write("</td>\r\n");
      out.write("\t                <td>");
      out.print(act.getActivityDate() );
      out.write("</td>\r\n");
      out.write("\t                <td>");
      out.print(act.getResult() );
      out.write("</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t            ");
}} 
      out.write("\r\n");
      out.write("\t            </tbody>\r\n");
      out.write("\t            <tfoot>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                <td colspan=\"5\">활동내역</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                </tfoot>\r\n");
      out.write("\t            </table>\r\n");
      out.write("\t            <!--//ui object -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} else{
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("어웨이팀이 결정되지 않았습니다.\r\n");
      out.write("</div>\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<br />\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary btn-block disabled\" id=\"btn_game_register\" onclick=\"fn_game_register();\" disabled>경기 신청</button>\r\n");
if(gameStatus && memberLoggedIn != null && tHome.getTeamName().equals(memberLoggedIn.getTeamname()) && "팀장".equals(memberLoggedIn.getGrade())) {
      out.write("\r\n");
      out.write("<button type=\"button\" class=\"btn btn-danger btn-block\" onclick=\"fn_delete_game();\">삭제</button>\r\n");
} 
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tif(");
      out.print(memberLoggedIn.getTeamname() == null);
      out.write("){\r\n");
      out.write("\t\t$(\"#btn_game_register\").removeClass('disabled').removeAttr(\"disabled\");\r\n");
      out.write("\t}else if(");
      out.print(!tHome.getTeamName().equals(memberLoggedIn.getTeamname()) && tAway == null);
      out.write("){\r\n");
      out.write("\t\t$(\"#btn_game_register\").removeClass('disabled').removeAttr(\"disabled\");\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
if(gameStatus){
      out.write("\r\n");
      out.write("function fn_game_register() {\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/game/waitTeam?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&gameNo=");
      out.print(g.getGameNo());
      out.write("\";\r\n");
      out.write("}\r\n");
}
      out.write('\r');
      out.write('\n');
if(gameStatus && memberLoggedIn != null && tHome.getTeamName().equals(memberLoggedIn.getTeamname()) && "팀장".equals(memberLoggedIn.getGrade())) {
      out.write("\r\n");
      out.write("function fn_delete_game() {\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/game/deleteGame?no=");
      out.print(g.getGameNo());
      out.write("\";\r\n");
      out.write("}\r\n");
}
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('ul.tabs li').click(function(){\r\n");
      out.write("\t\tvar tab_id = $(this).attr('data-tab');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('ul.tabs li').removeClass('current');\r\n");
      out.write("\t\t$('.tab-content').removeClass('current');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(this).addClass('current');\r\n");
      out.write("\t\t$(\"#\"+tab_id).addClass('current');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("var map = new naver.maps.Map(\"map\", {\r\n");
      out.write("    center: new naver.maps.LatLng(");
      out.print(place[2]);
      out.write(',');
      out.print(place[3]);
      out.write("),\r\n");
      out.write("    zoom: 10,\r\n");
      out.write("    mapTypeControl: true\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var infoWindow = new naver.maps.InfoWindow({\r\n");
      out.write("    anchorSkew: true\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("map.setCursor('grap');\r\n");
      out.write("\r\n");
      out.write("function searchCoordinateToAddress(latlng) {\r\n");
      out.write("    var tm128 = naver.maps.TransCoord.fromLatLngToTM128(latlng);\r\n");
      out.write("\r\n");
      out.write("    infoWindow.close();\r\n");
      out.write("\r\n");
      out.write("    naver.maps.Service.reverseGeocode({\r\n");
      out.write("        location: tm128,\r\n");
      out.write("        coordType: naver.maps.Service.CoordType.TM128\r\n");
      out.write("    }, function(status, response) {\r\n");
      out.write("        if (status === naver.maps.Service.Status.ERROR) {\r\n");
      out.write("            return alert('Something Wrong!');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var items = response.result.items,\r\n");
      out.write("            htmlAddresses = [];\r\n");
      out.write("\r\n");
      out.write("        for (var i=0, ii=items.length, item, addrType; i<ii; i++) {\r\n");
      out.write("            item = items[i];\r\n");
      out.write("            addrType = item.isRoadAddress ? '[도로명 주소]' : '[지번 주소]';\r\n");
      out.write("\r\n");
      out.write("            htmlAddresses.push((i+1) +'. '+ addrType +' '+ item.address);\r\n");
      out.write("            htmlAddresses.push('&nbsp&nbsp&nbsp -> '+ item.point.x +','+ item.point.y);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        infoWindow.setContent([\r\n");
      out.write("                '<div style=\"padding:10px;min-width:200px;line-height:150%;\">',\r\n");
      out.write("                '<h4 style=\"margin-top:5px;\">검색 좌표 : '+ response.result.userquery +'</h4><br />',\r\n");
      out.write("                htmlAddresses.join('<br />'),\r\n");
      out.write("                '</div>'\r\n");
      out.write("            ].join('\\n'));\r\n");
      out.write("\t\t\r\n");
      out.write("        infoWindow.open(map, latlng);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function searchAddressToCoordinate(address) {\r\n");
      out.write("    naver.maps.Service.geocode({\r\n");
      out.write("        address: address\r\n");
      out.write("    }, function(status, response) {\r\n");
      out.write("        if (status === naver.maps.Service.Status.ERROR) {\r\n");
      out.write("            return alert('Something Wrong!');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var item = response.result.items[0],\r\n");
      out.write("            addrType = item.isRoadAddress ? '[도로명 주소]' : '[지번 주소]',\r\n");
      out.write("            point = new naver.maps.Point(item.point.x, item.point.y);\r\n");
      out.write("\r\n");
      out.write("        infoWindow.setContent([\r\n");
      out.write("                '<div style=\"padding:10px;min-width:200px;line-height:150%;\">',\r\n");
      out.write("                '<h4 style=\"margin-top:5px;\">검색 주소 : '+ response.result.userquery +'</h4><br />',\r\n");
      out.write("                addrType +' '+ item.address +'<br />',\r\n");
      out.write("                '<a href=\"https://map.naver.com/?eX='+point.x+'&eY='+point.y+'&eText='+item.address+'&sY=&sText=\" target=\"_blank\">길찾기</a></br>',\r\n");
      out.write("                '</div>'\r\n");
      out.write("            ].join('\\n'));\r\n");
      out.write("        map.setCenter(point);\r\n");
      out.write("        infoWindow.open(map, point);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function initGeocoder() {\r\n");
      out.write("    searchAddressToCoordinate('");
      out.print(place[0]);
      out.write("');\r\n");
      out.write("}\r\n");
      out.write("naver.maps.onJSContentLoaded = initGeocoder;\r\n");
      out.write("</script>\r\n");
      out.write("<br /><br />\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer id=\"footer\">\r\n");
      out.write("        <div id=\"footer-wrapper\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img id=\"footer-image\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/headerImage.png\" /></a>\r\n");
      out.write("            <p>팀명 : 투톱체제<br>\r\n");
      out.write("          \t팀원 : 김대연, 최지수, 박희영, 배성인, 이연경<br>\r\n");
      out.write(" \t\t\t주소 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 4층</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('	');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
