/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-20 03:05:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dleague.member.model.vo.*;
import com.dleague.member.model.vo.*;
import com.dleague.member.model.vo.*;
import com.dleague.region.model.vo.*;
import java.util.*;

public final class memberEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1526783235618L));
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1526785090854L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1526380612202L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.dleague.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.dleague.region.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
 Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
   String param = (String)request.getAttribute("param");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Do+Hyeon|Nanum+Gothic\" rel=\"stylesheet\">\r\n");
      out.write("<title>DLeague</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\theader#header{ \r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height:119px; \r\n");
      out.write("\t    padding:10px 0 0 0;\r\n");
      out.write("\t    background: white;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t    top: 0px;\r\n");
      out.write("\t    left: 0px;\r\n");
      out.write("\t    border-bottom: 1px solid #f3f3f3;\r\n");
      out.write("\t    z-index: 150;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#header-div{\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height:41px;\r\n");
      out.write("\t    background: #f3f3f3;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t    top: 0px;\r\n");
      out.write("\t    left: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.header-div-wrap{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    height: 41px;\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    background: #f3f3f3;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.header-div-wrapping-nav{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    height: 77px;\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    background: white;\r\n");
      out.write("\t    top: 31px;\r\n");
      out.write("\t}\r\n");
      out.write("\timg#header-image{\r\n");
      out.write("\t    height: 77px;\r\n");
      out.write("\t}\r\n");
      out.write("\theader#header nav{\r\n");
      out.write("\t    float: right;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.main-nav{\r\n");
      out.write("\t    display:table;\r\n");
      out.write("\t    padding:0px; /*ul태그가 가진 기본padding초기화*/\r\n");
      out.write("\t    margin-top: 23px;\r\n");
      out.write("\t    margin-bottom: 0px;\r\n");
      out.write("\t    vertical-align: baseline;\r\n");
      out.write("\t    list-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-list{\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    padding-top: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover{\r\n");
      out.write("\t    border-bottom: 3px solid rgb(64,128,183); \r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover>div{\r\n");
      out.write("\t    border-top: 3px solid rgb(64,128,183); \r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover>a{\r\n");
      out.write("\t    color: rgb(64,128,183); \r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-list:hover div.main-nav-sub{\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-list>a{\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    padding: 0 0 19px;\r\n");
      out.write("\t    margin: 0 35px;\r\n");
      out.write("\t    font-size: 20px;\r\n");
      out.write("\t    color: #121212;\r\n");
      out.write("\t    font-family: 'Do Hyeon', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-list>a:link{\r\n");
      out.write("\t    text-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\tul#header-list {\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    float:right;\r\n");
      out.write("\t    display:table;\r\n");
      out.write("\t    padding:0px; /*ul태그가 가진 기본padding초기화*/\r\n");
      out.write("\t    margin:auto;\r\n");
      out.write("\t    margin-top: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul#header-list li{\r\n");
      out.write("\t    display:inline;\r\n");
      out.write("\t    list-style-type:none;\r\n");
      out.write("\t    padding:10px;\r\n");
      out.write("\t    font-size: 11px;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\tul#header-list li a{\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t    font-size: 9px;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    color:black;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-sub-li{\r\n");
      out.write("\t    list-style-type:none;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    padding-bottom: 10px;\r\n");
      out.write("\t    padding-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main-nav-sub-ul{\r\n");
      out.write("\t    padding: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.main-nav-sub{\r\n");
      out.write("\t    border: 1px solid rgb(64,128,183);\r\n");
      out.write("\t    display: none;\r\n");
      out.write("\t    background: white;\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-sub-li a{\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t    font-size: 15px;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    color:black;\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-sub-li:hover{\r\n");
      out.write("\t    background: rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tli.main-nav-sub-li:hover>a{\r\n");
      out.write("\t    color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t/*section-center*/\r\n");
      out.write("\tsection#center{\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    min-height: 960px;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    padding-top: 168px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tnav#nav{\r\n");
      out.write("\t    float: left;\r\n");
      out.write("\t    width: 175px;\r\n");
      out.write("\t    padding: 12px 0 0 14px;\r\n");
      out.write("\t    margin-right: 45px;\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\th3#nav-header{\r\n");
      out.write("\t    font-size: 23px;\r\n");
      out.write("\t    width: 115px;\r\n");
      out.write("\t    margin: 0 0 30px 15px;\r\n");
      out.write("\t    padding-bottom: 25px;\r\n");
      out.write("\t    border-bottom: 4px solid rgb(64,128,183);\r\n");
      out.write("\t    color: #111;\r\n");
      out.write("\t    line-height: 1.3;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list{\r\n");
      out.write("\t    margin-left: 15px;\r\n");
      out.write("\t    list-style: none;\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t    margin-left: 15px; \r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t    border: 0;\r\n");
      out.write("\t    font: inherit;\r\n");
      out.write("\t    vertical-align: baseline;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list li{\r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t    margin-bottom: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list li>a{\r\n");
      out.write("\t    display: block;\r\n");
      out.write("\t    font-size: 17px;\r\n");
      out.write("\t    color: #7c7c7c;\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\ta#nav-selected{\r\n");
      out.write("\t    color: rgb(64,128,183);\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\tsection#content{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    display:inline-block;\r\n");
      out.write("\t    margin:2px;\r\n");
      out.write("\t    width:750px;\r\n");
      out.write("\t    min-height: 300px;\r\n");
      out.write("\t    background:white;\r\n");
      out.write("\t    padding-left:10px;\r\n");
      out.write("\t    left: 206px;\r\n");
      out.write("\t}\r\n");
      out.write("\tul.nav-list li>a:hover{\r\n");
      out.write("\t    font-weight: bolder;\r\n");
      out.write("\t    color: rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tul.main-nav>li.main-nav-list a#header-selected{\r\n");
      out.write("\t    color:rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tul.main-nav>li.header-selected{\r\n");
      out.write("\t    border-bottom: 3px solid rgb(64,128,183);\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter#footer{\r\n");
      out.write("\t    background:#222;\r\n");
      out.write("\t    padding:5px;\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    height: 220px;\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter#footer p {\r\n");
      out.write("\t    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("\t    color:gray;\r\n");
      out.write("\t    text-align:center;\r\n");
      out.write("\t    font-size:15px;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    top: 80px;\r\n");
      out.write("\t    left: 307px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#footer-wrapper{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    width: 960px;\r\n");
      out.write("\t    height: 220px;\r\n");
      out.write("\t    margin: 0 auto;         \r\n");
      out.write("\t}\r\n");
      out.write("\timg#footer-image{\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    height: 77px;\r\n");
      out.write("\t    top: 54px;\r\n");
      out.write("\t    left: 170px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("<<<<<<< HEAD\n");
      out.write("<script>\r\n");
      out.write("=======\n");
      out.write("<script>\n");
      out.write(">>>>>>> branch 'master' of https://github.com/raccoon200/semi_project.git\n");
if(memberLoggedIn!=null) { 
      out.write(" \r\n");
      out.write("<<<<<<< HEAD\n");
      out.write("=======\n");
      out.write("\r\n");
      out.write(">>>>>>> branch 'master' of https://github.com/raccoon200/semi_project.git\n");
      out.write("\r\n");
      out.write("<<<<<<< HEAD\n");
      out.write("=======\n");
}
      out.write("\r\n");
      out.write("\n");
      out.write(">>>>>>> branch 'master' of https://github.com/raccoon200/semi_project.git\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <div id=\"header-div\">\r\n");
      out.write("            <div class=\"header-div-wrap\">\r\n");
      out.write("                <ul id=\"header-list\">\r\n");
      out.write("\t\t\t\t");
if(memberLoggedIn==null) {
      out.write("\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t    <li>|</li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginPage\">로그인</a></li>\r\n");
      out.write("\t\t\t\t ");
} else if("admin".equals(memberLoggedIn.getUserId())) { 
      out.write("\r\n");
      out.write("\t\t\t\t    <li>");
      out.print(memberLoggedIn.getUserId() );
      out.write("님 환영합니다!</li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t    <li>|</li>\r\n");
      out.write("\t\t\t\t    <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminPage\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t ");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t    <li>");
      out.print(memberLoggedIn.getUserId() );
      out.write("님 환영합니다!</li>\r\n");
      out.write("\t\t\t\t       <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"header-div-wrapping-nav\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img id=\"header-image\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/headerImage.png\" /></a>\r\n");
      out.write("            <nav>\r\n");
      out.write("            <ul class=\"main-nav\">\r\n");
      out.write("\t\t\t   <li id=\"main-nav-notice\" class=\"main-nav-list \"><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("               \r\n");
      out.write("               <li id=\"main-nav-board\" class='main-nav-list ");
      out.print(param=="freeBoard"||param=="regionBoard"||param=="complainBoard"?"header-selected":"");
      out.write("'>\r\n");
      out.write("                   <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/freeBoard\" id='");
      out.print(param=="freeBoard"||param=="regionBoard"||param=="complainBoard"?"header-selected":"");
      out.write("'>게시판</a>\r\n");
      out.write("                   <div class=\"main-nav-sub\" id=\"main-nav-sub-board\">\r\n");
      out.write("                       <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                           <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/freeBoard\" >자유게시판</a></li>\r\n");
      out.write("                           <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/regionBoard\" >지역게시판</a></li>\r\n");
      out.write("                           <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/complainBoard\">신고게시판</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                   </div>  \r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"main-nav-register\" class='main-nav-list ");
      out.print(param=="gameRegister"||param=="myGameList"?"header-selected":"");
      out.write("'>\r\n");
      out.write("               \t  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/gameRegister\" id='");
      out.print(param=="gameRegister"||param=="myGameList"?"header-selected":"");
      out.write("'>경기등록</a>\r\n");
      out.write("                  <!-- 경기등록  -->\r\n");
      out.write("                  <div class=\"main-nav-sub\" id=\"main-nav-sub-register\">\r\n");
      out.write("                     <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/gameRegister\">경기등록</a></li>\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/myGameList\">내팀경기일정</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"main-nav-search\" class='main-nav-list ");
      out.print(param=="teamSearch"?"header-selected":"");
      out.write("'>\r\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/teamSearch\" id='");
      out.print(param=="teamSearch"?"header-selected":"");
      out.write("'>검색</a>\r\n");
      out.write("                  <!-- 검색 -->\r\n");
      out.write("                  <div class=\"main-nav-sub\" id=\"main-nav-sub-search\">\r\n");
      out.write("                     <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/teamSearch\" >팀 검색</a></li>\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/gameSearchList\">경기 검색</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li id=\"main-nav-mypage\" class='main-nav-list ");
      out.print(param=="memberInfo"||param=="memberTeamInfo"?"header-selected":"");
      out.write("'>\r\n");
      out.write("          \t\t  \r\n");
      out.write("                  <a href=\"");
      out.print((memberLoggedIn!=null)?request.getContextPath()+"/member/memberInfoPage":"javascript:window.alert('로그인 후 사용가능합니다.')");
      out.write("\" id='");
      out.print(param=="memberInfo"||param=="memberTeamInfo"?"header-selected":"");
      out.write("'>마이페이지</a>\r\n");
      out.write("                  <!-- 마이페이지 -->\r\n");
      out.write("                  <div class=\"main-nav-sub\" id=\"main-nav-sub-mypage\">\r\n");
      out.write("                     <ul class=\"main-nav-sub-ul\">\r\n");
      out.write("                         ");
if(memberLoggedIn!=null) {
      out.write(" \r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberInfoPage\">내 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        <!-- onclick=\"return fn_validate_team_info();\" -->\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamInfoPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&userId=");
      out.print(memberLoggedIn.getUserId() );
      out.write("\" >내 팀 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamManagementPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\">내 팀 관리</a></li>\r\n");
      out.write("                        ");
 if("선수".equals(memberLoggedIn.getGrade())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"main-nav-sub-li\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamCreate?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\">팀생성</a><li>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                         ");
} 
      out.write(" \r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               \r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("         </nav>\r\n");
      out.write("         <!-- 메인메뉴 끝 -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("console.log(\"");
      out.print(param);
      out.write("\");\r\n");
      out.write("function fn_deleteOK() {\r\n");
      out.write("\tif(confirm(\"정말로 삭제하시겠습니까?\")) return true;\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("      <section id=\"center\">\r\n");
      out.write("\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 공지사항 -->\r\n");
      out.write("\t\t\t");
 if(param=="notice"){ 
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">공지사항</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a id=\"nav-selected\" href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t<!-- 게시판 -->\n");
      out.write("\t\t\t");
 if(param=="freeBoard" || param=="regionBoard" || param=="complain") {
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<h3 id=\"nav-header\">게시판</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a id='");
      out.print(param=="freeBoard"?"nav-selected":"");
      out.write("' href=\"");
      out.print(request.getContextPath() );
      out.write("/board/freeBoard\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t<li><a id='");
      out.print(param=="regionBoard"?"nav-selected":"");
      out.write("' href=\"");
      out.print(request.getContextPath() );
      out.write("/board/regionBoard\">지역게시판</a></li>\r\n");
      out.write("\t\t\t\t<li><a id='");
      out.print(param=="complain"?"nav-selected":"");
      out.write("' href=\"");
      out.print(request.getContextPath() );
      out.write("/board/complainBoard\">신고게시판</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<!-- 로그인/회원가입 -->\r\n");
      out.write("\t\t\t");
if(param=="login" || param=="enroll") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">계정</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginPage\" id=");
      out.print(param=="login"?"nav-selected":"");
      out.write(">로그인</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll\" id=");
      out.print(param=="enroll"?"nav-selected":"");
      out.write(">회원가입</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="passwordCheck") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id = \"nav-header\">비밀번호 찾기</h3>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="passwordUpdate") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">비밀번호 변경</h3>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="gameRegister"||param=="myGameList") {
      out.write("\r\n");
      out.write("\t\t\t<!-- 경기등록  -->\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">경기등록</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/gameRegister\" id='");
      out.print(param=="gameRegister"?"nav-selected":"");
      out.write("'>경기등록</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/game/myGameList\" id='");
      out.print(param=="myGameList"?"nav-selected":"");
      out.write("'>내팀경기일정</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="teamSearch"||param=="teamSearchList") {
      out.write("\r\n");
      out.write("\t\t\t<!-- 검색 -->\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">검색</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/teamSearch\" id='");
      out.print(param=="teamSearch"?"nav-selected":"");
      out.write("'>팀검색</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/search/gameSearchList\" id='");
      out.print(param=="teamSearchList"?"nav-selected":"");
      out.write("'>경기검색</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="memberTeamMemberManagement" || param=="memberTeamGameAcceptPage" || param=="memberTeamMemberAcceptPage" || param=="memberTeamActivityPage" || param=="memberTeamDelete") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">팀 관리</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamManagement?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamMemberManagement"?"nav-selected":"");
      out.write("'>팀원 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamMemberAcceptPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamMemberAcceptPage"?"nav-selected":"");
      out.write("'>팀원 수락</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamGameAcceptPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamGameAcceptPage"?"nav-selected":"");
      out.write("'>팀 경기 수락</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamActivityPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamActivityPage"?"nav-selected":"" );
      out.write("'>팀 활동 결과 처리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberTeamDelete?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("\" id='");
      out.print(param=="memberTeamDelete"?"nav-selected":"" );
      out.write("' onclick = \"return fn_deleteOK();\">팀 삭제</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(param=="memberInfo" || param=="memberTeamInfo" || param=="memberTeamManagement" || param=="memberTeamCreate") {
      out.write("\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">마이페이지</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberInfoPage\" id=\"");
      out.print(param=="memberInfo"?"nav-selected":"" );
      out.write("\" >내 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamInfoPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\" id=\"");
      out.print(param=="memberTeamInfo"?"nav-selected":"" );
      out.write("\">내 팀 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamManagementPage?teamName=");
      out.print(memberLoggedIn.getTeamname());
      out.write("&userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\" id=\"");
      out.print(param=="memberTeamManagement"?"nav-selected":"" );
      out.write("\">내 팀 관리</a></li>\r\n");
      out.write("\t\t\t\t");
 if("선수".equals(memberLoggedIn.getGrade())) { 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberTeamCreate?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\" id=\"");
      out.print(param=="memberTeamCreate"?"nav-selected":"");
      out.write("\">팀생성</a></li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul> \r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(param=="adminPage" || param=="adminPageTeam" ||param=="adminAccept") {
      out.write("\r\n");
      out.write("\t\t\t<!-- 관리자페이지 -->\r\n");
      out.write("\t\t\t<h3 id=\"nav-header\">관리자페이지</h3>\r\n");
      out.write("\t\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/adminPage\" id=\"");
      out.print(param=="adminPage"?"nav-selected":"" );
      out.write("\" >회원 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/adminPageTeam\" id=\"");
      out.print(param=="adminPageTeam"?"nav-selected":"" );
      out.write("\">팀 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/adminAccept\" id=\"");
      out.print(param=="adminAccept"?"nav-selected":"" );
      out.write("\">팀 수락</a></li>S\r\n");
      out.write("\t\t\t</ul>  \r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<section id=\"content\">");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    Member m = (Member)request.getAttribute("member");
	List<Region> regionList = (List<Region>)request.getAttribute("regionList");
    
      out.write("\r\n");
      out.write("        <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- font awesome -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom Style -->\r\n");
      out.write("    <style>\r\n");
      out.write("    table{align:center;}\r\n");
      out.write("    #profile{position: relative; left:-110px; top:0px;}\r\n");
      out.write("    #profileImg{width:100px; height:150px;} \r\n");
      out.write("#imgsection{position: relative; left:535px; top:-265px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#userId_{width:80%; display:inline-block;}\r\n");
      out.write("\r\n");
      out.write("#passwordCheckTd{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("}\r\n");
      out.write("#passwordCheckMessage {\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:10px;\r\n");
      out.write("\tleft:10px;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("<script>\r\n");
      out.write("function fn_checkIdDuplicate(){\r\n");
      out.write("   \r\n");
      out.write("   var userId = $(\"#userId_\").val().trim();\r\n");
      out.write("   if(userId.length<4){\r\n");
      out.write("      alert('아이디는 4글자 이상부터 가능합니다. \\n (영대소문자와 숫자포함 4~12자)');\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   var url = \"");
      out.print(request.getContextPath());
      out.write("/member/checkIdDuplicate\";\r\n");
      out.write("   var title = \"checkIdDuplicate\";\r\n");
      out.write("   var status = \"left=350px, top=100px, width=300px, height=200px\";\r\n");
      out.write("   var popup = window.open(\"\",title,status);\r\n");
      out.write("   \r\n");
      out.write("   var checkIdDuplicateFrm = document.checkIdDuplicateFrm;\r\n");
      out.write("   checkIdDuplicateFrm.userId.value=userId;\r\n");
      out.write("   \r\n");
      out.write("   checkIdDuplicateFrm.target = title;\r\n");
      out.write("   checkIdDuplicateFrm.action = url;\r\n");
      out.write("   checkIdDuplicateFrm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_birthday() {\r\n");
      out.write("\t if($(\"#birthday\").val().length!=6 || Number($(\"#birthday\").val())==NaN) {\r\n");
      out.write("\t\t/* alert(\"생년월일은 6자리숫자로입력해주세요\"); */\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar year = Number($(\"#birthday\").val().substr(0,2));\r\n");
      out.write("\tvar month = Number($(\"#birthday\").val().substr(2,2));\r\n");
      out.write("\tvar day = Number($(\"#birthday\").val().substr(4,2));\r\n");
      out.write("\tconsole.log(\"year=\"+year);\r\n");
      out.write("\tvar isleap = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0 ));\r\n");
      out.write("\tif(month <1 || month >12){\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t} else if(day <1 || day >31) {\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}  /* else if ((month==4 || month==6 || month==9 || month=11) && day==31){\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}  */ else if(month ==2) {\r\n");
      out.write("\t    if (day >29 || (day==29 && !isleap)){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t} \r\n");
      out.write("\t return true;\r\n");
      out.write("}\r\n");
      out.write("function passwordCheckFunction() {\r\n");
      out.write("\tvar password = $('#password_').val();\r\n");
      out.write("\tvar passwordchk = $('#password_chk').val();\r\n");
      out.write("\tif ( password != passwordchk) {\r\n");
      out.write("\t\t$('#passwordCheckMessage').html('비밀번호가 서로 일치하지 않습니다.');\r\n");
      out.write("\t} else if(password == passwordchk){\r\n");
      out.write("\t\t$('#passwordCheckMessage').html('');\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function fn_checked() {\r\n");
      out.write("\tconsole.log(\"안녕\");\r\n");
      out.write("\tvar idtext = document.getElementById(\"userId_\");\r\n");
      out.write("\tvar patext = document.getElementById(\"password_\");\r\n");
      out.write("\tvar cpatext = document.getElementById(\"password_chk\");\r\n");
      out.write("\tvar mtext = document.getElementById(\"email_\");\r\n");
      out.write("\tvar m1text = document.getElementById(\"email_1\");\r\n");
      out.write("\tvar nametext = document.getElementById(\"userName\");\r\n");
      out.write("\tvar bitext = document.getElementById(\"birthday\");\r\n");
      out.write("\tvar phtext = document.getElementById(\"phone\");\r\n");
      out.write("\tvar intro = document.getElementById(\"profile\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar userId = idtext.value;\r\n");
      out.write("\tvar password = patext.value;\r\n");
      out.write("\tvar password_chk = cpatext.value;\r\n");
      out.write("\tvar email_ = mtext.value;\r\n");
      out.write("\tvar email_1 = m1text.value;\r\n");
      out.write("\tvar userName = nametext.value;\r\n");
      out.write("\tvar birthday = bitext.value;\r\n");
      out.write("\tvar phone = phtext.value;\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log(userId);\r\n");
      out.write("\tconsole.log(password);\r\n");
      out.write("\tconsole.log(password_chk);\r\n");
      out.write("\tconsole.log(\"email =\"+email_+\"@\"+email_1);\r\n");
      out.write("\tconsole.log(userName);\r\n");
      out.write("\tconsole.log(birthday);\r\n");
      out.write("\tconsole.log(phone);\r\n");
      out.write("\tvar regExp0 = /^[a-zA-Z0-9]{4,12}$/;\r\n");
      out.write("\tvar regExp1 = /^[a-zA-Z0-9]{4,12}$/;\r\n");
      out.write("\t//id와 비밀번호의 유효성 검사\r\n");
      out.write("\tvar regExp2 = /[a-z0-9]{2,}$/;\r\n");
      out.write("\tvar regExp3 = /[a-z0-9]{2,}\\.[a-z0-9]{2,}$/;\r\n");
      out.write("\t//email의 직접입력부분 유효성검사\r\n");
      out.write("\tvar regname = /^[가-힝]{2,5}$/;\r\n");
      out.write("\t// 이름 유효성 검사\r\n");
      out.write("  \tvar regExp4 = /[0-9]{6,6}$/; \r\n");
      out.write("\t// 주민번호 유효성 검사\r\n");
      out.write("\tvar regph = /^01[0-9]{8,9}$/s;\r\n");
      out.write("\t// 폰번호유효성 검사\r\n");
      out.write("\tconsole.log(\"userid =\"+userId);\r\n");
      out.write("\tif(!regExp0.test(userId))\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Id를 제대로 입력해주세요.\");\r\n");
      out.write("\t\tidtext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if($(\"[name=idValid]\").val() != 1){\r\n");
      out.write("\t\talert(\"ID중복체크를 해주세요.\")\r\n");
      out.write("\t\tidtext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(!regExp1.test(password))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"비밀번호를 제대로 입력해주세요.\");\r\n");
      out.write("\t\tpatext.value=\"\";\r\n");
      out.write("\t\tpatext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if(!(password_chk.slice(0,password_chk.length) === password.slice(0,password.length)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"비밀번호가 동일하지 않습니다.\");\r\n");
      out.write("\t\tcpatext.value = \"\";\r\n");
      out.write("\t\tcpatext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if ((password_chk.slice(0, password_chk.length) === userId.slice(0, userId.length)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"비밀번호가 ID와 동일하면 안됩니다.\");\r\n");
      out.write("\t\tpatext.value= \"\";\r\n");
      out.write("\t\tpatext.focus();\r\n");
      out.write("\t\tcpatext.value= \"\";\r\n");
      out.write("\t\tcpatext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if(!regname.test(userName))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"이름을 제대로 입력해주세요.\");\r\n");
      out.write("\t\t\tnametext.value =\"\";\r\n");
      out.write("\t\t\tnametext.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\telse if(!fn_birthday()||!regExp4.test(birthday)) {\r\n");
      out.write("\t\talert(\"생년월일을 제대로 입력해주세요.\"); \r\n");
      out.write("\t\tbitext.value=\"\";\r\n");
      out.write("\t\tbitext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(!regph.test(phone))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"전화번호를 확인해주세요.\");\r\n");
      out.write("\t\tphtext.value=\"\";\r\n");
      out.write("\t\tphtext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if (!regExp2.test(email_))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"이메일을 확인해주세요.\");\r\n");
      out.write("\t\tmtext.value= \"\";\r\n");
      out.write("\t\tmtext.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if (!regExp3.text(email_1))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"직접입력부분을 확인해주세요.\");\r\n");
      out.write("\t\tm1text.value=\"\";\r\n");
      out.write("\t\tm1text.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\telse if (intro.value ==\"\"){\r\n");
      out.write("\t\talert(\"자기 소개란을 100자 내외로 입력해주세요.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<section id = \"enroll-container\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"memberEnrollFrm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnrollEnd\" onsubmit=\"return fn_checked();\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("<table class = \"table table-bordered table-hover\" style=\"text-align: center; border : 1px solid #dddddd\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th colspan=\"3\"><h4 style=\"font-weight : bold;\">회원 가입</h4></th>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">아이디</h5></td>\r\n");
      out.write("\r\n");
      out.write("<td style=\"text-align:left;\">\r\n");
      out.write("<input class=\"form-control\" type=\"text\" name=\"userId\" id=\"userId_\" placeholder = \"아이디를 입력하세요 . (영대소문자와 숫자포함 4~12자)\" value =\"\" required/>\r\n");
      out.write("\r\n");
      out.write("<input class = \"btn btn-primary pull-right\" value=\"중복검사\" id=\"btn-idValid\" onclick=\"fn_checkIdDuplicate()\" style=\"width:100px;\" />\r\n");
      out.write("<input type = \"hidden\" name=\"idValid\" value=\"0\" />\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">비밀번호</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input class=\"form-control\" type=\"password\" name=\"password\" id=\"password_\" placeholder =\"비밀번호를 입력하세요. (영대소문자와 숫자포함 4~12자)\" onkeyup=\"passwordCheckFunction();\" value =\"\"/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">비밀번호 확인</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input class=\"form-control\" type=\"password\" id=\"password_chk\" placeholder =\"위와 동일한 비밀번호를 입력하세요.\" onkeyup=\"passwordCheckFunction();\" value =\"\" />\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">이름</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input class=\"form-control\" type=\"text\" name=\"userName\" id=\"userName\" value =\"\" placeholder =\"(이름 5글자내외)\"/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">생년월일</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input class=\"form-control\" type=\"text\" name=\"birthday\" id=\"birthday\" value =\"\" placeholder=\"(주민번호 앞 6자리)\" maxlength=\"6\"/> \r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">휴대폰</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input class=\"form-control\" type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\"(-없이)01012345678\" maxlength=\"11\" value =\"\"/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">이메일</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"email1\"  id=\"email_\" value =\"\" >@\r\n");
      out.write("<input type=\"text\" name = \"email2\" id=\"email_1\" disabled value=\"naver.com\" value = \"\">\r\n");
      out.write("<select name=\"selectEmail\" id=\"selectEmail\"  style = \"height:30px\">\r\n");
      out.write("<option value=\"1\">직접입력</option>\r\n");
      out.write("<option value=\"naver.com\" selected>naver.com</option>\r\n");
      out.write("<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("<option value=\"hotmail.com\">hotmail.com</option>\r\n");
      out.write("<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("</select>\r\n");
      out.write("<script>\r\n");
      out.write("//자동완성 함수\r\n");
      out.write("$(\"#selectEmail\").change(function() {\r\n");
      out.write("   $(\"#selectEmail option:selected\").each(function() {\r\n");
      out.write("      if($(this).val() =='1') {\r\n");
      out.write("         $(\"#email_1\").val(\"\");\r\n");
      out.write("         $(\"#email_1\").attr(\"disabled\",false);\r\n");
      out.write("         }else {\r\n");
      out.write("            $(\"#email_1\").val($(this).text());\r\n");
      out.write("            $(\"#email_1\").attr(\"disabled\",true);\r\n");
      out.write("         }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">거주지역</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("            <select name=\"regioncode\" id=\"\" style = \"height:30px\">\r\n");
      out.write("            ");
if(regionList!=null && !regionList.isEmpty()){
            for(int i=0; i<regionList.size(); i++) {
               Region region = regionList.get(i);
            
      out.write("\r\n");
      out.write("               <option value=\"");
      out.print(region.getRegionCode());
      out.write('"');
      out.write('>');
      out.print( region.getRegionName());
      out.write("</option>\r\n");
      out.write("            ");

               }
            } 
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("            </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style =\"width:110px;\"><h5 style=\"font-weight : bold;\">프로필</h5></td>\r\n");
      out.write("<td>\r\n");
      out.write("<textarea id=\"profile\" name=\"profile\" maxlength=\"2048\" cols=\"50\"style=\"height:180px;\" placeholder = \"자기소개란\"></textarea>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td style = \"text-align: left\" colspan=\"3\" id=\"passwordCheckTd\"><h5 style =\"color: red;\" id =\"passwordCheckMessage\" ></h5><input class = \"btn btn-primary pull-right\" type=\"submit\" value=\"회원가입\"><input class = \"btn btn-primary pull-right\" type=\"reset\" value=\"취소\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write(" <section id=\"imgsection\">\r\n");
      out.write("<input type=\"image\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/profile/default.jpg\" id=\"profileImg\"/>\r\n");
      out.write("<br /> \r\n");
      out.write("<div style=\"position:relative;\">\r\n");
      out.write(" <input type=\"file\" name=\"up_file\" id=\"up_file\" accept=\".gif, .jpg, .png\" onchange=\"fn_fileUpload(this);\"  /> \r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</form>\r\n");
      out.write("<form name=\"checkIdDuplicateFrm\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"userId\"/>\r\n");
      out.write("</form>\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("$(function (){\r\n");
      out.write("});\r\n");
      out.write("$(\"[name=up_file]\").change(function(){ \r\n");
      out.write("\t//$(this).val()은 선택한 파일명임.\r\n");
      out.write("\tif($(\"#up_file\").val()==\"\") {\r\n");
      out.write("\t\t$('#profileImg').attr('src', \"");
      out.print(request.getContextPath() );
      out.write("/images/profile/default.jpg\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(this).val()==\"\"){\r\n");
      out.write("\t\t$(\"#fname\").show();\r\n");
      out.write("\t}\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$(\"#fname\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("});\t\r\n");
      out.write("function fn_fileUpload(value){\r\n");
      out.write("\r\n");
      out.write("    if(value.files && value.files[0]) {\r\n");
      out.write("   \t\tvar value2 = $(\"#up_file\").val();\r\n");
      out.write("   if(value2==\"\") {\r\n");
      out.write("        $('#profileImg').attr('src', \"");
      out.print(request.getContextPath() );
      out.write("/images/profile/default.jpg\");\r\n");
      out.write("     } \r\n");
      out.write("        if(value.files && value.files[0]) {\r\n");
      out.write("            var reader = new FileReader();\r\n");
      out.write("            reader.onload = function (e) {\r\n");
      out.write("                 $('#profileImg').attr('src', e.target.result);         \r\n");
      out.write("    \t\t\t}\r\n");
      out.write("            }\r\n");
      out.write("            reader.readAsDataURL(value.files[0]);\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<footer id=\"footer\">\r\n");
      out.write("        <div id=\"footer-wrapper\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img id=\"footer-image\" src=\"");
      out.print(request.getContextPath() );
      out.write("/images/headerImage.png\" /></a>\r\n");
      out.write("            <p>팀명 : 투톱체제<br>\r\n");
      out.write("          \t팀원 : 김대연, 최지수, 박희영, 배성인, 이연경<br>\r\n");
      out.write(" \t\t\t주소 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 4층</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
